Conflux-Chain/helios

- packages/background/src/db-schema.js
- packages/rpcs/wallet_addVault/index.js
- packages/rpcs/wallet_addVault/package.json
- packages/spec/index.js
- yarn.lock
if user giving a base32 address vault, mark it as cfx only vault, don't create ethHexAddress on the corresponding account when creating it from the vault
For hex address public vault, store the original hex address. Create a normal account with ethHexAddress and convert it to 0x-prefixed address as cfxHexAddress.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/19)
> feat(vault): add cfxOnly to public vault

- .yarn/versions/4b7ef94c.yml
- packages/background/src/index.integration.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/678)
> test: more robust integration test

- .yarn/versions/fb113636.yml
- packages/dapp-cross-space/src/manage/index.tsx
- packages/dapp-cross-space/src/manage/useConflux/ConfluxManage.ts
- packages/dapp-cross-space/src/manage/useEvm/EvmManage.ts
- packages/dapp-cross-space/src/manage/useFluent/FluentManage.ts
- packages/dapp-cross-space/src/manage/useFluent/index.tsx
- packages/dapp-cross-space/src/pages/Nav/index.tsx
- packages/dapp-cross-space/types/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/681)
> feat: delete evmtestnet

- .env
- .yarn/versions/2231a8d3.yml
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/ui/provider-api/index.js
1. emit network events on start
2. cache last item in compatible provide event stream
3. only emit accountsChanged event when the app/currentAccount do chagned
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/724)
> fix: compatible provider api

- .yarn/versions/811c830b.yml
- packages/db/src/main/cfxjs/db/queries.cljs
PORTAL-2709
Note:
This PR is from Lugu Lake, Yunnan, China
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/793)
> fix: escape fuzzy regexp

- .yarn/versions/e6121e9c.yml
- packages/rpcs/cfx_chainId/index.js
PORTAL-2867
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/881)
> fix: wrong chainid logic

- .yarn/versions/bc6b013d.yml
- packages/consts/index.js
- packages/db/src/main/cfxjs/db/migrations/m6.cljs
- packages/rpcs/eth_signTransaction/index.js
PORTAL-3046
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/968)
> fix(sign): add none standard field after estimate

- .yarn/versions/997beb9d.yml
- packages/ledger/const.js
- packages/ledger/ethereum.js
some APIs have already changed, but they are compatible
- `isAppOpen(chainName)`
- `openApp(ledgerAppName)`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1009)
> feat: support ledger eSpace app

- .yarn/versions/59c47033.yml
- packages/rpcs/wallet_setAppCurrentNetwork/index.js
sometimes, when you authorize a hardware ledger account under ethereum to a dapp site, when you switch to conflux network, there will be a error: you cannot get addr
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1038)
> fix(PORTAL-3114):switch network error

- .yarn/versions/996b1940.yml
- packages/rpcs/cfx_signTransaction/index.js
fullnode change the estimate rpc, when tx data not including gasPrice and gasLimit will estimate with gasPrice`1drip` and gasLimit `1500w`, otherwise, will estimate with supplied data. So should estimate before cfx_gasPrice, avoiding estimate with gasPrice 1Gdrip and return an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1039)
> fix: estimate error

- .yarn/versions/f9c50e83.yml
- packages/popup/src/components/Avatar.js
- packages/popup/src/components/DappProgressHeader.js
- packages/popup/src/components/TokenItem.js
- packages/popup/src/hooks/index.js
- packages/popup/src/hooks/useApi.js
- packages/popup/src/pages/AuthorizedWebsite/components/DappItem.js
- packages/popup/src/pages/ConfirmTransaction/components/InfoList.js
- packages/popup/src/pages/History/components/HistoryItem.js
- packages/popup/src/pages/Home/components/AccountList.js
- packages/popup/src/pages/Home/components/AddToken.js
- packages/popup/src/pages/Home/components/CurrentDapp.js
- packages/popup/src/pages/Home/components/useAuthorizedAccountIdIcon.js
- packages/popup/src/pages/Home/index.js
1.PORTAL-3102
2.PORTAL-3103
3.PORTAL-3101
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1036)
> fix: fix bugs

- .yarn/versions/497814b4.yml
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/rpcs/wallet_setCurrentNetwork/index.js
- packages/rpcs/wallet_updateAccount/index.js
- packages/rpcs/wallet_updateAccount/package.json
- yarn.lock
1. delete app if is only authed acc
2. switch acc and revoke auth if is selected and authed acc
3. revoke auth if is non-selected authed acc
4. switch to first authed acc that has addr under current network
5. check if is last none hw account before hidden
PORTAL-3138
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1063)
> feat: handle dapp auth accounts on account hidden

- .yarn/versions/e1619a66.yml
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
- packages/rpcs/wallet_handleUnfinishedETHTx/index.js
1. we set tx to failed if tx with same nonce get confirmed, this action
won't trigger the notification
2. setTxXXX fns will check tx status before make the tx, and will return
nil(undefined) if is tx in end state already.
3. this won't fix PORTAL-3357, check the detail in PORTAL-3357 for more
PORTAL-3357
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1220)
> fix: only show notifications if failed none silently

- .yarn/versions/b05d9237.yml
- packages/db/src/main/cfxjs/db/queries.cljs
don't count none confirmed tx and external tx when fetching external tx
from scan
PORTAL-3390
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1239)
> fix: external tx logic affected by none confirmed tx

- .yarn/versions/aa00b5c3.yml
- packages/rpcs/eth_estimate1559Fee/index.js
- packages/rpcs/eth_feeHistory/index.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1381)
> Espace 1559

- .yarn/versions/5c772db8.yml
- package.json
- packages/ledger/package.json
- scripts/webpack.config.cjs
- scripts/webpack.config.dev.mjs
- scripts/webpack.config.prod.mjs
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1396)
> chore: optimize package size

- .github/workflows/pre-release.yaml
- .github/workflows/prod-release.yaml
- .yarn/versions/bb95e59f.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1398)
> build: update github action config

- .yarn/versions/9c11183a.yml
- packages/background/src/index.integration.test.js
- packages/rpcs/cfx_call/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1421)
> chore: add more fields to cfx_call

- .yarn/versions/afe58fcb.yml
- packages/ledger/conflux.js
- packages/ledger/ethereum.js
- packages/ledger/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1434)
> Update ledger sdk and replace webusb with webhid

- .yarn/versions/afe58fcb.yml
- packages/background/src/index.integration.test.js
- packages/rpcs/cfx_signTransaction/index.js
- packages/test-helpers/package.json
- packages/test-helpers/setupNetwork.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1437)
> add v1 version ledger app support

- packages/db/src/main/cfxjs/db/queries.cljs
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
- packages/rpcs/wallet_handleUnfinishedETHTx/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1460)
> fix: error handle

- .yarn/versions/01a87f4a.yml
- package.json
- packages/background/src/rpc-engine-opts.js
- packages/inner-utils/env.js
- packages/rpc-engine/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1506)
> fix firefox build not match

- .yarn/versions/049eabeb.yml
- packages/background/src/service-worker.js
- packages/content-script/indexTemplate.js
- packages/inpage/setup-inpage-provider.js
- packages/inpage/take-over-portal.js
- packages/manifest/manifestv3.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1517)
> feat: inject inpage.js by chrome content-script
