- package.json
- packages/popup/src/App.js
- scripts/snowpack.postcss.popup.plugin.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/4)
> add @tailwindcss/jit

- packages/data-format/README.md
- packages/data-format/index.js
- packages/data-format/index.test.js
- packages/data-format/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/7)
> feat: add data format

- .github/workflows/nodejs.yaml
- codecov.yml
- jest.config.js
- packages/db/index.js
- packages/db/src/db.test.js
- packages/db/src/main/cfxjs/db/core.cljc
- packages/db/src/main/cfxjs/db/core.cljs
- packages/db/src/main/cfxjs/db/datafy.cljc
- packages/db/src/main/cfxjs/db/impl/entity.cljc
- packages/db/src/main/cfxjs/db/schema.cljc
- shadow-cljs.edn
with schema:
```javascript
const schema = {
vault: {
type: {
doc: 'Type of vault: public, pk, mnemonic',
},
data: {
doc: 'Encrypted vault data',
},
accounts: {
doc: 'Accounts belong to this vault',
many: true,
ref: true,
component: true,
},
},
account: {
hexAddress: {
identity: true,
doc: 'Account hex address',
},
vault: {
ref: true,
doc: 'Entity ID of vault',
},
},
}
const dbConnection = createdb(schema)
```
get
```javascript
const {
getById,
updateById,
deleteById
createVault,
createAccount,
getVault,
getOneVault,
getVaultByType,
getVaultByData,
getAccount,
getOneAccount,
getAccountByVault,
getAccountByHexAddress,
deleteVault,
deleteOneVault,
updateVault,
updateOneVault,
} = dbConnection
```
check out the `db.test.js` file for more usage
---
This change is [<img …
> feat(db): add basic db CRUD functions

- .github/workflows/nodejs.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/6)
> ci: add maven cache for clojure dependencies to gh workflow

- packages/background/src/index.js
- packages/json-rpc-error/README.md
- packages/json-rpc-error/index.js
- packages/json-rpc-error/index.test.js
- packages/json-rpc-error/package.json
- packages/rpc-engine/index.js
- packages/rpc-engine/package.json
- packages/rpc-engine/src/error.js
- packages/rpc-engine/src/error.test.js
- packages/rpcs/wallet_addVault/index.js
- packages/rpcs/wallet_addVault/index.test.js
- packages/rpcs/wallet_unlock/index.js
- packages/rpcs/wallet_unlock/index.test.js
- packages/rpcs/wallet_validatePassword/index.test.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/9)
> feat: add @cfxjs/json-rpc-error

- packages/rpcs/wallet_importAddress/README.md
- packages/rpcs/wallet_importAddress/index.js
- packages/rpcs/wallet_importAddress/index.test.js
- packages/rpcs/wallet_importAddress/package.json
- packages/rpcs/wallet_validatePassword/index.test.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/11)
> feat: add wallet_importAddress, support use address as vault

- jest.config.js
- packages/background/src/index.test.js
- packages/rpcs/wallet_validatePassword/index.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/13)
> refactor: integration test spec.js -> test.js

- packages/rpcs/wallet_validatePassword/index.test.js
- packages/spec/src/main/cfxjs/spec/core.cljs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/14)
> fix: address generator in spec

- packages/rpcs/wallet_isLocked/README.md
- packages/rpcs/wallet_isLocked/index.js
- packages/rpcs/wallet_isLocked/index.test.js
- packages/rpcs/wallet_isLocked/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/17)
> feat(rpc): add wallet_isLocked

- packages/spec/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/18)
> feat(spec): add dbid

- jest.config.js
- packages/hdkey/README.md
- packages/hdkey/index.js
- packages/hdkey/index.test.js
- packages/hdkey/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/20)
> feat(hdkey): add @cfxjs/hdkey for process hd wallet

- packages/hdkey/index.js
- packages/hdkey/index.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/21)
> fix(hdkey): index error, make it async function

- packages/background/src/db-schema.js
- packages/rpcs/wallet_createAccount/README.md
- packages/rpcs/wallet_createAccount/index.js
- packages/rpcs/wallet_createAccount/index.test.js
- packages/rpcs/wallet_createAccount/package.json
- yarn.lock
PORTAL-662
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/22)
> feat(rpc): add wallet_createAccount

- jest.config.js
- packages/rpcs/wallet_generateAddress/index.js
- scripts/dev.js
- scripts/jest-test-jsdom-env.js
- scripts/jest-test-node-env.js
- scripts/prod.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/23)
> fix(wallet_generateAddress): error in input schema

- jest.config.js
- packages/get-all-rpcs/README.md
- packages/get-all-rpcs/index.js
- packages/get-all-rpcs/index.test.js
- packages/get-all-rpcs/package.json
- packages/rpcs/wallet_createAccount/index.js
- packages/rpcs/wallet_generateAddress/index.js
- packages/rpcs/wallet_generateAddress/index.test.js
- packages/rpcs/wallet_importAddress/index.js
- packages/spec/index.js
- packages/spec/src/main/cfxjs/spec/core.cljs
- packages/spec/src/main/cfxjs/spec/doc.cljs
- scripts/dev.js
- scripts/jest-test-jsdom-env.js
- scripts/jest-test-node-env.js
- scripts/prod.js
- scripts/snowpack.base.config.js
- shadow-cljs.edn
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/24)
> feat(spec): add function to generate doc from spec

- .github/workflows/nodejs.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/29)
> ci: support empty release in workflow

- .yarn/versions/6f5b1777.yml
- .yarnrc.yml
- packages/background/src/index.js
- packages/errors/index.js
- packages/json-rpc-error/index.js
- packages/rpc-engine/index.js
- packages/rpc-engine/index.test.js
- packages/rpc-engine/middleware.js
- packages/rpc-engine/middlewares/call-rpc.js
- packages/rpc-engine/middlewares/index.js
- packages/rpc-engine/middlewares/inject-rpc-store.js
- packages/rpc-engine/middlewares/inject-wallet-db.js
- packages/rpc-engine/middlewares/validate-json-rpc.js
- packages/rpc-engine/middlewares/validate-rpc-method.js
- packages/rpc-engine/middlewares/validate-rpc-params.js
- packages/rpc-engine/package.json
- packages/rpc-engine/src/error.js
- packages/rpc-engine/src/error.test.js
- packages/spec/index.js
- packages/spec/src/main/cfxjs/spec/core.cljs
- packages/transducers/index.js
- packages/ui/provider-api/index.js
- shadow-cljs.edn
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/32)
> refactor(rpc-engine): use rstream-graph for middlewares

- .github/workflows/nodejs.yaml
- scripts/create-pkg-release-pr
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/37)
> ci: use gh replace hub, add npm token for npm publish

- .yarn/versions/0a1fcda7.yml
- package.json
- packages/background/package.json
- packages/background/snowpack.config.cjs
- packages/background/src/index.js
- packages/background/src/init-db.js
- packages/background/src/rpc-engine-opts.js
- packages/base32-address/index.js
- packages/base32/index.js
- packages/cache-rpc/index.js
- packages/cache-rpc/package.json
- packages/rpc-engine/middlewares/fetch.js
- packages/rpc-engine/middlewares/validate-rpc-data.js
- packages/rpc-engine/package.json
- packages/rpcs/cfx_epochNumber/index.js
- packages/rpcs/cfx_epochNumber/index.test.js
- packages/rpcs/cfx_getAccount/index.js
- scripts/dev.js
- scripts/prod.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/40)
> feat: add epoch block cache strategy, use new snowpack

- .yarn/versions/75c568f2.yml
- packages/data-format/index.js
- packages/data-format/index.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/47)
> feat: change cfx decimal func to token decimal func

- .yarn/versions/5c3075df.yml
- packages/background/src/index.integration.test.js
- packages/background/src/index.js
- packages/rpc-engine/middlewares/validate-rpc-data.js
- packages/rpcs/cfx_epochNumber/index.js
- packages/rpcs/cfx_getAccount/index.js
- packages/rpcs/cfx_getBalance/index.js
- packages/rpcs/cfx_getCode/index.js
- packages/rpcs/eth_blockNumber/index.js
- packages/rpcs/eth_getBalance/index.js
- packages/rpcs/eth_getCode/index.js
- packages/rpcs/eth_getTransactionCount/index.js
- packages/rpcs/wallet_createAccount/index.js
- packages/rpcs/wallet_discoverAccounts/index.js
- packages/rpcs/wallet_generateAddress/index.js
- packages/rpcs/wallet_generateMnemonic/index.js
- packages/rpcs/wallet_generatePrivateKey/index.js
- packages/rpcs/wallet_getBalance/index.js
- packages/rpcs/wallet_getNextNonce/index.js
- packages/rpcs/wallet_isLocked/index.js
- packages/rpcs/wallet_unlock/index.js
- packages/rpcs/wallet_validatePassword/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/50)
> feat: add network/internal method/wallet lock state validation

- .github/workflows/nodejs.yaml
- .yarn/versions/eef3e48d.yml
- packages/rpcs/wallet_importAll/index.js
1. import ext polyfill only in browser
2. only deploy doc/storybook in dev branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/66)
> fix: fix doc build

- .github/release-drafter.yml
- .github/workflows/debug-release.yaml
- .github/workflows/deploy-doc.yaml
- .github/workflows/deploy-storybook.yaml
- .github/workflows/pre-release.yaml
- .github/workflows/publish-npm-package.yml
- .github/workflows/push-check.yaml
- .github/workflows/release.yaml
- .github/workflows/version-check.yaml
- .gitignore
- package.json
- scripts/create-zip
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/68)
> ci: auto release workflow

- .github/scripts/commentPRDebugRelease.js
- .github/scripts/deleteOldDebugRelease.js
- .github/scripts/getDebugRelease.js
- .github/workflows/comment-on-release.yaml
- .github/workflows/debug-release.yaml
- .github/workflows/deploy-doc.yaml
- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/69)
> ci: auto-comment-on-release

- .github/release-drafter.yml
- .github/workflows/debug-release.yaml
- .github/workflows/pre-release.yaml
- .yarn/versions/6fb2fbc4.yml
- packages/popup/package.json
- packages/popup/src/App.js
- packages/popup/src/index.js
- packages/popup/src/store/befores.js
- packages/popup/src/store/index.js
- packages/popup/src/store/init-store.js
- packages/popup/src/store/rpc-config.js
- packages/popup/src/store/useStore.js
- packages/ui/useRPC/index.js
- packages/ui/useRPC/setup-ext-provider.js
- packages/ui/useRPC/setup-provider.js
- yarn.lock
- Please approve this after you fully understand what's going on.
- Please do point out places that might be wrong/misleading.
- Please give some suggestions if there are 
- better documentation
- better implementation
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/81)
> feat: add useStore

- .github/workflows/debug-release.yaml
- .yarn/versions/377503a0.yml
- packages/popup/package.json
- packages/popup/src/App.js
- packages/popup/src/store/useStore.js
- packages/ui/useRPC/index.js
- packages/ui/useRPC/setup-ext-provider.js
- yarn.lock
remove extra render
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/86)
> fix(useStore): cache accessing with ref

- packages/popup/src/hooks/zustand.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/96)
> fix: run beforeSet out of useEffect

- .github/release-drafter-pre.yml
- .github/workflows/debug-release.yaml
- .github/workflows/pre-release.yaml
- packages/popup/src/hooks/zustand.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/97)
> fix(zustand): remove beforeSet, add a saferGet dev only fn

- .github/scripts/commentPRDebugRelease.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/108)
> ci: update prev comment instead of creating a new one

- .yarn/versions/52197918.yml
- packages/background/package.json
- packages/background/src/index.integration.test.js
- packages/background/src/rpc-engine-opts.js
- packages/rpcs/wallet_deleteApp/README.md
- packages/rpcs/wallet_deleteApp/index.js
- packages/rpcs/wallet_deleteApp/package.json
- packages/rpcs/wallet_getCurrentViewingApp/README.md
- packages/rpcs/wallet_getCurrentViewingApp/index.js
- packages/rpcs/wallet_getCurrentViewingApp/package.json
- packages/rpcs/wallet_getNetwork/README.md
- packages/rpcs/wallet_getNetwork/index.js
- packages/rpcs/wallet_getNetwork/package.json
- packages/webextension/index.js
- packages/webextension/tab.js
- yarn.lock
PORTAL-956
PORTAL-955
PORTAL-954
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/114)
> feat: add missing rpcs in pref dapp interaction pr

- .yarn/versions/95459a52.yml
- packages/browser-extension/manifest.json.mustache
- packages/rpc-engine/middlewares/validate-rpc-data.js
- packages/rpcs/wallet_addVault/index.js
- packages/rpcs/wallet_getCurrentViewingApp/index.js
- packages/rpcs/wallet_importAddress/index.js
- packages/rpcs/wallet_importMnemonic/index.js
- packages/rpcs/wallet_importPrivateKey/index.js
PORTAL-962
PORTAL-934
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/116)
> fix: broken doc build

- .yarn/versions/bd68dd54.yml
- packages/background/snowpack.config.cjs
- scripts/prod.js
- scripts/snowpack.base.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/123)
> chore: optimize prod build

- .yarn/versions/6f2a1189.yml
- packages/popup/src/App.js
- packages/rpcs/wallet_addVault/index.js
- packages/rpcs/wallet_getCurrentViewingApp/index.js
- packages/webextension/tab.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/129)
> fix: unlock wallet after creating vault

- .yarn/versions/2acf1091.yml
- packages/popup/src/hooks/index.js
- packages/popup/src/pages/Home/components/AccountList.js
add balance in account list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/145)
> feat：Batch balance

- .yarn/versions/da2e4c91.yml
- package.json
- packages/contract-abis/777.js
- packages/contract-method-name/cfx-name.js
- packages/contract-method-name/cfx-name.test.js
- packages/contract-method-name/constance.js
- packages/contract-method-name/index.js
- packages/contract-method-name/package.json
- yarn.lock
add 777 abis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/187)
> feat: add 777 abis

- .yarn/versions/6e894fb9.yml
- packages/estimate-tx/index.js
- packages/estimate-tx/package.json
- yarn.lock
PORTAL-1329
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/195)
> fix: bn16 support 0x-prefixed hex decimal

- .yarn/versions/09d9869c.yml
- packages/background/src/init-db.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/197)
> fix: image url PORTAL-1331

- .yarn/versions/9d8fc9c7.yml
- packages/popup/src/components/LanguageNav.js
- packages/popup/src/components/PasswordInput.js
- packages/popup/src/constants/index.js
- packages/popup/src/hooks/useApi.js
- packages/popup/src/pages/ConfirmAddSuggestedToken/index.js
- packages/popup/src/pages/CreateSeed/ConfirmSeed.js
- packages/popup/src/pages/DappSwitchNetwork/index.js
- packages/popup/src/pages/Home/components/AccountList.js
- packages/popup/src/pages/ImportPrivateKey/index.js
- packages/popup/src/pages/ImportSeedPhrase/index.js
- packages/popup/src/pages/SelectCreateType/components/CreateTypeItem.js
- packages/popup/src/pages/SetPassword/components/SetPasswordForm.js
- packages/popup/src/pages/SetPassword/components/index.js
- packages/popup/src/pages/SetPassword/index.js
1.PORTAL-1225
2.remove empty objcet in fallbackdata
3.ui bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/204)
> Fix: import account bug

- .yarn/versions/dee04d31.yml
- packages/token-list-schema/index.js
https://github.com/Uniswap/token-lists/blob/9ebe28f4047a79c1f39380f6f21e7f0bde831cc7/src/tokenlist.schema.json#L235
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/212)
> feat: token name length to 40

- packages/estimate-tx/index.js
- packages/popup/src/hooks/index.js
PORTAL-1397
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/219)
> feat: add cfxGetFeeData, update estiamte-tx

- .yarn/versions/c98b996a.yml
- package.json
- packages/ui/useRPC/index.js
- yarn.lock
PORTAL-1451
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/229)
> fix: new provider api

- .yarn/versions/66131e31.yml
- packages/popup/src/components/NumberInput.js
- packages/ui/data-format/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/249)
> fix bug: PORTAL-1455

- .yarn/versions/7cfddaca.yml
- packages/popup/src/components/NumberInput.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/251)
> fix: warning

- .yarn/versions/493b4e73.yml
- packages/popup/src/pages/ConnectSite/index.js
PORTAL-1516
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/253)
> fix: fix logic bugs

- .github/scripts/assert-fullnode-error-message-check.mjs
- .github/scripts/getPRRelease.js
- .github/workflows/debug-release.yaml
- .yarn/versions/23e4d918.yml
- packages/browser-extension/manifest.json.mustache
- packages/db/src/main/cfxjs/db/queries.cljs
- scripts/before_all.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/270)
> feat: optimize tx query, update manifest.json

- .yarn/versions/7672a2f0.yml
- packages/db/src/main/cfxjs/db/queries.cljs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/272)
> feat: count only for tx query

- .yarn/versions/936eabf0.yml
- packages/background/src/db-schema.js
- packages/rpc-engine/src/error.js
- scripts/before_all.js
1. delete token list when network deleted
2. fix csp for firefox in dev env
3. fix dev only error msg format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/274)
> fix: minor fixes

- .yarn/versions/6ba7c838.yml
- packages/rpcs/cfx_signTypedData_v4/doc.js
- packages/rpcs/cfx_signTypedData_v4/index.js
PORTAL-1582
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/277)
> fix: better err msg and doc for sign typed data

- .yarn/versions/125eb1b1.yml
- packages/popup/src/pages/EditGasFee/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/276)
> fix: PORTAL-1579

- .yarn/versions/536e0a8d.yml
- packages/popup/src/components/GasFee.js
- packages/popup/src/pages/ConfirmTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/282)
> fix: dapp edit gas bug

- .yarn/versions/1faef8a9.yml
- packages/rpcs/wallet_requestUnlockUI/index.js
PORTAL-1682
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/297)
> fix: typo casuing wrong unlock page in prod

- packages/estimate-tx/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/301)
> fix: get sponsorship info with custom gas/storage

- .yarn/versions/434c0162.yml
- packages/popup/package.json
- packages/popup/src/pages/SendTransaction/index.js
- packages/tx-history-checker/README.md
- packages/tx-history-checker/index.js
- packages/tx-history-checker/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/300)
> fix: PORTAL-1685, add no tx history alert

- .yarn/versions/a7a784ea.yml
- .yarn/versions/cb944608.yml
- packages/background/src/db-schema.js
- packages/background/src/index.js
- packages/conflux-tx-error/index.js
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/popup/src/components/HomeNav.js
- packages/rpcs/cfx_sendTransaction/index.js
- packages/rpcs/wallet_addConfluxChain/doc.js
- packages/rpcs/wallet_addEthereumChain/doc.js
- packages/rpcs/wallet_addEthereumChain/index.js
- packages/rpcs/wallet_enrichConfluxTx/index.js
- packages/rpcs/wallet_getPendingAuthRequest/index.js
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
- packages/rpcs/wallet_watchAsset/index.js
1. typo in handle unfinished tx causing wallet won't resend droped tx
1. remove redundant interval on wallet startup
1. add `resendAt` to tx to rate limit the resend action
1. add `processed` lock to authReq to avoid process same authReq twice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/299)
> fix: tx workflow

- .yarn/versions/a7ac5152.yml
- packages/popup/src/pages/Home/components/useAuthorizedAccountIdIcon.js
fix   PORTAL-1690
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/308)
> fix:  fix PORTAL-1690

- .yarn/versions/49a693da.yml
- packages/popup/src/pages/Home/components/HomeTokenList.js
- packages/webextension/popup.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/311)
> fix: fixed overlap and scroll issue

- .yarn/versions/67e035ac.yml
- packages/db/src/main/cfxjs/db/queries.cljs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/316)
> fix: db check id

- .yarn/versions/3022d7c1.yml
- package.json
- packages/background/src/db-schema.js
- packages/db/src/main/cfxjs/db/core.cljs
- packages/db/src/main/cfxjs/db/migrate.cljs
- packages/db/src/main/cfxjs/db/migrations/core.cljs
- packages/db/src/main/cfxjs/db/migrations/m2.cljs
- packages/db/src/main/cfxjs/db/preloads.cljs
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/rpcs/wallet_addVault/index.js
- packages/rpcs/wallet_getImportHardwareWalletInfo/index.js
- packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js
- shadow-cljs.edn
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/318)
> feat: add device to vault

- .yarn/versions/c5dfd04c.yml
- packages/background/package.json
- packages/background/src/rpc-engine-opts.js
- packages/rpcs/cfx_sendTransaction/index.js
- packages/rpcs/cfx_sendTransaction/package.json
- packages/rpcs/cfx_signTransaction/index.js
- packages/rpcs/cfx_signTxWithLedgerNanoS/README.md
- packages/rpcs/cfx_signTxWithLedgerNanoS/index.js
- packages/rpcs/cfx_signTxWithLedgerNanoS/package.json
- packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js
- packages/signature/index.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/322)
> feat: add cfx_signTxWithLedgerNanoS

- .yarn/versions/6ef39575.yml
- packages/ledger/conflux.js
- packages/ledger/const.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/324)
> feat: add getDeviceInfo api

- .yarn/versions/0274fa06.yml
- packages/popup/src/App.js
- packages/popup/src/hooks/index.js
- packages/popup/src/hooks/useApi.js
- packages/popup/src/pages/ConfirmTransaction/index.js
- packages/popup/src/pages/SendTransaction/components/TokenAndAmount.js
- packages/popup/src/pages/SendTransaction/index.js
- packages/popup/src/stores/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/330)
> fix: token amount, error boundary

- .yarn/versions/9f5bf4d0.yml
- packages/db/src/main/cfxjs/db/queries.cljs
- shadow-cljs.edn
PORTAL-1658
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/340)
> fix: delete useless token when tokenlist updated

- .yarn/versions/319c89ec.yml
- packages/popup/package.json
- packages/popup/src/App.css
- packages/popup/src/App.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/336)
> feat: add router level transition

- .yarn/versions/91505f65.yml
- packages/popup/src/constants/index.js
- packages/popup/src/locales/en.js
- packages/popup/src/pages/ConfirmTransaction/components/HwTransactionResult.js
- packages/popup/src/pages/ConfirmTransaction/components/index.js
- packages/popup/src/pages/ConfirmTransaction/index.js
- packages/ui/components/Modal/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/345)
> fix: PORTAL-1822 and add hw tx modal

- .yarn/versions/f7ca5701.yml
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/rpcs/wallet_lock/index.js
- packages/rpcs/wallet_lock/index.test.js
- packages/rpcs/wallet_setCurrentAccount/index.js
- packages/rpcs/wallet_unlock/index.js
- packages/rpcs/wallet_unlock/index.test.js
1. fix typo in get-network
2. fix db failed to check by id bug
PORTAL-1799
PORTAL-1743
PORTAL-1807
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/346)
> fix: db fix

- .yarn/versions/7a0199ba.yml
- packages/popup/src/components/SlideCard.js
- packages/popup/src/hooks/useApi.js
- packages/popup/src/pages/History/components/HistoryItem.js
- packages/popup/src/pages/History/index.js
- packages/popup/src/pages/ImportPrivateKey/index.js
- packages/popup/src/pages/ImportSeedPhrase/index.js
- packages/popup/src/pages/SetPassword/components/SetPasswordForm.js
- packages/popup/src/pages/Unlock/index.js
- packages/popup/src/utils/index.js
- scripts/tailwind.config.js
1.PORTAL-1812
2.PORTAL-1732
3.PORTAL-1735
4.PORTAL-1787
5.optimize mask fade animation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/349)
> fix: fix  bugs

- .yarn/versions/7179299f.yml
- packages/ui/provider-api/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/352)
> fix: no need to init confluxJS.provider after connect

- .yarn/versions/948c3cdd.yml
- packages/popup/src/pages/Home/components/AddToken.js
- packages/popup/src/pages/Home/components/CurrentDapp.js
PORTAL-1845
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/360)
> fix: forget custom token address in addToken

- .yarn/versions/ca17830e.yml
- packages/popup/src/pages/SetPassword/components/SetPasswordForm.js
- packages/popup/src/pages/ViewData/index.js
1.PORTAL-1849
2.PORTAL-1857
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/367)
> fix: fix bugs

- .yarn/versions/2e5060e9.yml
- packages/popup/src/App.js
- packages/popup/src/components/DappFooter.js
- packages/popup/src/pages/ConfirmTransaction/index.js
- packages/popup/src/pages/CreateSeed/ConfirmSeed.js
- packages/popup/src/pages/CurrentSeed/index.js
- packages/popup/src/pages/ImportPrivateKey/index.js
- packages/popup/src/pages/ImportSeedPhrase/index.js
- packages/popup/src/pages/Unlock/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/370)
> feat: add logo loading

- .env.production
- .github/release-drafter-pre.yml
- .github/release-drafter-prod.yml
- .github/release-drafter.yml
- .github/workflows/debug-release.yaml
- .github/workflows/pre-release.yaml
- .yarn/versions/29e44676.yml
- .yarn/versions/f520706f.yml
- packages/background/package.json
- packages/background/src/db-schema.js
- packages/background/src/index.js
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/popup/package.json
- packages/popup/src/index.js
- packages/rpc-engine/index.js
- packages/rpc-engine/middlewares/call-rpc.js
- packages/rpc-engine/src/error.js
- packages/rpcs/cfx_sendTransaction/index.js
- packages/rpcs/cfx_signTransaction/index.js
- packages/rpcs/wallet_importMnemonic/index.js
- packages/rpcs/wallet_zeroAccountGroup/index.js
- packages/sentry/README.md
- packages/sentry/computeDefaultOptions.js
- packages/sentry/index.js
- packages/sentry/package.json
- packages/ui/provider-api/index.js
- packages/webextension/index.js
- packages/webextension/runtime.js
- yarn.lock
PORTAL-1754
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/362)
> fix: confluxJS.provider

- .yarn/versions/d7cad271.yml
- packages/rpcs/cfx_gasPrice/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/373)
> feat: use gas station for mainnet

- .yarn/versions/d15af05d.yml
- packages/popup/src/locales/en.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/385)
> fix: fixed typo issue of invaildConfirmPassword

- .yarn/versions/cfbce5c8.yml
- packages/rpc-engine/middlewares/call-rpc.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/388)
> fix: guard only inpage method in call-rpc

- scripts/before_all.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/391)
> fix: wrong version format

- .yarn/versions/f2933cb3.yml
- packages/rpcs/wallet_requestPermissions/index.js
PORTAL-1888
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/393)
> fix: accountsChanged event when expanding auth

- .yarn/versions/0e334e6d.yml
- packages/rpcs/wallet_validateAppPermissions/index.js
PORTAL-1841
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/394)
> fix: optimize validateAppPermissions error message

- .yarn/versions/1a0732fa.yml
- packages/db/src/main/cfxjs/db/queries.cljs
PORTAL-1983
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/397)
> fix: compare nonce with goog.math.Long

- .yarn/versions/60290c43.yml
- packages/popup/src/components/PasswordInput.js
- packages/popup/src/pages/SetPassword/components/SetPasswordForm.js
- packages/popup/src/pages/Unlock/index.js
- packages/popup/src/utils/index.js
- packages/ui/components/Input/index.js
1. PORTAL-1988
2. PORTAL-1934
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/402)
> feat: add features

- .yarn/versions/b198f5d9.yml
- packages/db/package.json
- packages/db/src/main/cfxjs/db/queries.cljs
- shadow-cljs.edn
- yarn.lock
PORTAL-2027
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/406)
> fix: db balance update bug

- .yarn/versions/b4c3f02f.yml
- packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/410)
> fix: ddata should be string when import hw account

- .yarn/versions/3c7cbf8b.yml
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/413)
> fix: don't set badge

- .yarn/versions/6788d3a9.yml
- packages/browser-extension/images/hardware-wallet-icon.svg
- packages/popup/src/locales/en.js
- packages/popup/src/pages/Home/index.js
- packages/popup/src/pages/SelectCreateType/index.js
PORTAL-2054
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/418)
> feat: replace hw icon

- .yarn/versions/de23a918.yml
- packages/json-rpc-error/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/420)
> fix: add missing error instance check

- .yarn/versions/4da0fc93.yml
- packages/rpcs/cfx_sendTransaction/index.js
- packages/rpcs/cfx_sendTransaction/package.json
- yarn.lock
PORTAL-2002
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/426)
> fix: override dapp gasprice on cfx mainnet

- .yarn/versions/cc336f40.yml
- packages/popup/src/pages/Home/components/AccountList.js
- packages/popup/src/pages/Home/components/useAuthorizedAccountIdIcon.js
PORTAL-2074
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/425)
> fix: show dapp icon

- .gitignore
- .yarn/versions/6ff32b1b.yml
- packages/popup/public/notification.html.mustache
- packages/popup/public/page.html.mustache
- packages/popup/public/popup.html.mustache
- packages/popup/snowpack.config.cjs
- packages/rpcs/wallet_userApprovedAuthRequest/package.json
- packages/rpcs/wallet_userRejectedAuthRequest/package.json
- packages/webextension/popup.js
- scripts/after_prod.js
- scripts/before_all.js
- scripts/snowpack.base.config.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/431)
> feat: use different html for different page

- .yarn/versions/8a87d8f7.yml
- packages/popup/src/hooks/useApi.js
- packages/popup/src/pages/Home/components/AddToken.js
- scripts/after_prod.js
PORTAL-2072
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/430)
> fix: refactor addToken

- .yarn/versions/32b0fb27.yml
- packages/base32-address/index.test.js
- packages/rpc-engine/middlewares/validate-rpc-data.js
- packages/rpc-engine/src/error.js
- packages/rpcs/wallet_enrichConfluxTx/index.js
PORTAL-1961
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/441)
> fix: support builtin contract

- .yarn/versions/28d7759c.yml
- packages/ledger/conflux.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/444)
> fix: several bugs

- .yarn/versions/05bee15c.yml
- packages/popup/src/components/NetworkContent.js
- packages/popup/src/hooks/useLoading/createPageLoading.js
- packages/popup/src/hooks/useLoading/createSpinLoading.js
- packages/popup/src/hooks/useLoading/index.css
- packages/popup/src/hooks/useLoading/index.js
- packages/popup/src/pages/CreateSeed/ConfirmSeed.js
- packages/popup/src/pages/CurrentSeed/index.js
- packages/popup/src/pages/ImportPrivateKey/index.js
- packages/popup/src/pages/ImportSeedPhrase/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/447)
> feat: Increase blur level of Page type Loading in some private scenes

- .yarn/versions/b8667534.yml
- packages/popup/src/components/DappFooter.js
- packages/popup/src/pages/ConfirmTransaction/components/HwTransactionResult.js
- packages/popup/src/pages/ConfirmTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/451)
> fix: handle the reject result when confirm in dapp

- .yarn/versions/83f7360a.yml
- packages/popup/src/components/DisplayBalance.js
- packages/popup/src/components/GasFee.js
- packages/popup/src/components/Text/index.css
- packages/popup/src/components/Text/index.js
- packages/popup/src/hooks/useDebouncedValue.js
- packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
- packages/popup/src/pages/ConfirmTransaction/index.js
- packages/ui/components/Button/__snapshots__/index.test.js.snap
- packages/ui/components/Button/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/464)
> fix: Confirm Transaction page data flicker bug

- .yarn/versions/ee784499.yml
- packages/popup/src/components/DisplayBalance.js
- packages/popup/src/hooks/useLoading/createPageLoading.js
- packages/popup/src/hooks/useLoading/createSpinLoading.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/468)
> Fix page loading

- .yarn/versions/cc65ae1a.yml
- packages/popup/src/components/HwAlert.js
- packages/popup/src/pages/ConfirmTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/473)
> fix: fix confirm button disabled

- .yarn/versions/bba52d0e.yml
- packages/popup/src/App.css
- packages/popup/src/App.js
- packages/popup/src/hooks/useLoading/createPageLoading.js
- packages/popup/src/hooks/useLoading/createSpinLoading.js
- packages/popup/src/pages/Home/components/CurrentDapp.js
- packages/popup/src/pages/Home/components/HomeTokenList.js
- packages/popup/src/pages/Home/index.css
- packages/popup/src/pages/Home/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/477)
> fix: some UX improve

- .yarn/versions/ea4a88cb.yml
- packages/popup/src/components/SlideCard.js
- packages/popup/src/hooks/index.js
- packages/popup/src/pages/ConnectSite/index.js
- packages/popup/src/pages/Error/index.js
- packages/popup/src/pages/Home/components/AccountList.js
- packages/popup/src/pages/Home/index.js
- packages/popup/src/pages/ImportHwAccount/index.js
- packages/popup/src/pages/ImportPrivateKey/index.js
- packages/popup/src/pages/ImportSeedPhrase/index.js
1.PORTAL-2266
2.PORTAL-2264
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/483)
> feat: add links and optimize animation

- .yarn/versions/b9ed7822.yml
- packages/rpcs/cfx_sendTransaction/index.js
- packages/rpcs/cfx_signTransaction/index.js
- packages/rpcs/wallet_userRejectedAuthRequest/index.js
PORTAL-2254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/484)
> fix: reject failed real sign

- .github/workflows/prod-release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/487)
> ci: prod release workflow

- .github/workflows/prod-release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/495)
> ci: merge main back to dev after prod release

- .env.production
- .github/workflows/pre-release.yaml
- .yarn/versions/88370c28.yml
- packages/rpcs/wallet_setCurrentNetwork/index.js
PORTAL-2282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/500)
> fix: notify unauthed site chainChanged as well

- .yarn/versions/1000e4e3.yml
- packages/popup/src/pages/Error/index.js
- packages/popup/src/pages/SendTransaction/index.js
add TokenAmount animation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/502)
> feat : add TokenAmount animation

- examples/basic-dapp/index.html
- examples/basic-dapp/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/505)
> feat: add deploy-contract to example

- .env
- .env.development
- .env.production
- .github/scripts/getPreReleaseNumber.js
- .github/workflows/pre-release.yaml
- .github/workflows/prod-release.yaml
- .yarn/versions/182a19e8.yml
- packages/browser-extension/manifest.json.mustache
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/rpc-engine/middlewares/call-rpc.js
- packages/rpc-engine/middlewares/fetch.js
- packages/rpc-engine/middlewares/inject-rpc-store.js
- packages/rpc-engine/middlewares/inject-wallet-db.js
- packages/rpc-engine/middlewares/validate-json-rpc-format.js
- packages/rpc-engine/middlewares/validate-rpc-data.js
- packages/rpc-engine/middlewares/validate-rpc-params.js
- scripts/before_all.js
- scripts/create-zip.cjs
- scripts/prod.js
- scripts/set_version_number
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/503)
> ci: refactor release workflow

- .github/scripts/getPreReleaseNumber.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/509)
> ci: pre release

- .yarn/versions/78fbd7cd.yml
- packages/popup/src/pages/SendTransaction/index.js
fix send amount  error shaking
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/510)
> fix: fix error shaking

- .yarn/versions/645b3354.yml
- packages/background/src/index.js
- packages/browser-extension/manifest.json.mustache
- packages/webextension/commands.js
- packages/webextension/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/514)
> feat: add shortcut for open large screen for debug

- .github/mergify.yml
- .github/release-drafter-pre.yml
- .github/scripts/getPreReleaseNumber.js
- .github/workflows/pre-release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/516)
> ci: debug pre release workflow

- .yarn/versions/cd4d71fa.yml
- packages/rpcs/wallet_registerSiteMetadata/index.js
- packages/rpcs/wallet_requestPermissions/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/517)
> feat: auto auth fluent dapp

- .yarn/versions/220f27e6.yml
- packages/popup/src/components/DappFooter.js
- packages/popup/src/components/DisplayBalance.js
- packages/popup/src/components/GasFee.js
- packages/popup/src/components/ProtectedRoute.js
- packages/popup/src/hooks/useLedger.js
- packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
- packages/popup/src/pages/ConfirmTransaction/components/InfoList.js
- packages/popup/src/pages/ConfirmTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/519)
> refactor: add classname, add state to pending auth route

- .yarn/versions/8f217fe4.yml
- packages/background/src/index.integration.test.js
- packages/rpcs/wallet_addNetwork/index.js
- packages/rpcs/wallet_createAddress/index.js
PORTAL-2358
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/521)
> fix: create addr pk to addr

- .yarn/versions/f0a26571.yml
- examples/basic-dapp/index.js
- packages/popup/src/components/TokenItem.js
- packages/popup/src/pages/ConfirmAddSuggestedToken/index.js
- packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
- packages/popup/src/pages/Home/components/AddToken.js
- packages/popup/src/pages/Home/components/HomeTokenList.js
- packages/popup/src/pages/SendTransaction/components/CurrentNetworkDisplay.js
- packages/popup/src/pages/SendTransaction/components/TokenAndAmount.js
- scripts/tailwind.config.js
1. PORTAL-2326
2. PORTAL-2329
3. PORTAL-2333
4. PORTAL-2335
5. PORTAL-2336
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/522)
> fix: ui check

- .yarn/versions/8c167b19.yml
- packages/popup/src/components/Text/index.js
https://github.com/reactjs/react-transition-group/releases/tag/v4.4.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/524)
> fix: frontend strict mode error

- .yarn/versions/de11b26e.yml
- packages/browser-extension/manifest.json.mustache
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/526)
> fix: json format

- .yarn/versions/018c22aa.yml
- packages/browser-extension/manifest.json.mustache
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/531)
> fix: manifest

- .yarn/versions/e579ef15.yml
- packages/background/src/db-schema.js
- packages/popup/src/components/DappFooter.js
- packages/popup/src/constants/index.js
- packages/popup/src/pages/ConfirmTransaction/components/HwTransactionResult.js
- packages/popup/src/pages/ConfirmTransaction/index.js
- packages/popup/src/pages/History/components/HistoryItem.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/533)
> fix: display send error detail

- .yarn/versions/a58789be.yml
- packages/estimate-tx/index.js
PORTAL-2375
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/536)
> fix: error when input upper case addr

- .yarn/versions/9f73516b.yml
- packages/popup/src/hooks/index.js
- packages/popup/src/pages/ConfirmTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/538)
> fix: PORTAL-2387

- .yarn/versions/43dc97bd.yml
- packages/browser-extension/manifest.json.mustache
PORTAL-2388
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/540)
> fix: default keybind to open big screen

- .yarn/versions/4ce43461.yml
- packages/popup/src/components/SlideCard.js
- packages/popup/src/components/TokenList.js
- packages/popup/src/pages/Home/components/AddToken.js
- packages/popup/src/pages/Home/components/CurrentAccount.js
- packages/popup/src/pages/Home/components/HomeTokenList.js
- packages/popup/src/pages/SendTransaction/components/TokenAndAmount.js
1. PORTAL-2291
2. PORTAL-2327
3. PORTAL-2280
4. adjust SlideCard padding bottom from pb-7 to pb-3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/543)
> fix: fixed bugs

- .yarn/versions/c7bd4351.yml
- packages/rpcs/wallet_addEthereumChain/index.js
PORTAL-2394
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/542)
> feat: support add network from popup

- .yarn/versions/cdbc9099.yml
- packages/popup/src/components/GasFee.js
- packages/popup/src/hooks/index.js
- packages/popup/src/pages/ConfirmTransaction/components/HwTransactionResult.js
- packages/popup/src/pages/ConfirmTransaction/components/InfoList.js
- packages/popup/src/pages/ConfirmTransaction/components/TransactionResult.js
- packages/popup/src/pages/ConfirmTransaction/index.js
- packages/popup/src/pages/EditGasFee/index.js
- packages/popup/src/pages/EditPermission/index.js
- packages/popup/src/pages/SendTransaction/index.js
- packages/popup/src/stores/index.js
PORTAL-2323
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/548)
> refactor: refactor useTxParams

- .yarn/versions/9da4cb40.yml
- package.json
- packages/background/package.json
- packages/background/src/rpc-engine-opts.js
- packages/rpc-epoch-ref/index.js
- packages/rpcs/cfx_getMaxGasLimit/README.md
- packages/rpcs/cfx_getMaxGasLimit/doc.js
- packages/rpcs/cfx_getMaxGasLimit/index.js
- packages/rpcs/cfx_getMaxGasLimit/package.json
- yarn.lock
fix cache of cfx_getBestBlockHash, cfx_getBlockByHash
PORTAL-2353
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/553)
> feat: new rpc method cfx_getMaxGasLimit

- .github/workflows/deploy-basic-dapp-demo.yaml
- .github/workflows/deploy-cross-space-dapp.yaml
- .github/workflows/deploy-doc.yaml
- .yarn/versions/dfa718b0.yml
- packages/built-in-network-icons/cfx.svg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/559)
> chore: icon typo

- .yarn/versions/d5d5d715.yml
- packages/dapp-cross-space/index.html
- packages/dapp-cross-space/src/assets/cfx.svg
- packages/dapp-cross-space/src/index.css
- packages/dapp-cross-space/src/manage/useEvm/EvmManage.ts
- packages/dapp-cross-space/src/manage/useFluent/FluentManage.ts
- packages/dapp-cross-space/src/pages/index.css
- packages/dapp-cross-space/src/pages/index.tsx
- packages/dapp-cross-space/vite.config.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/561)
> fix: cross-space close minify and change some style

- .github/mergify.yml
- .github/workflows/cross-space-dapp-push-check.yaml
- .github/workflows/deploy-cross-space-dapp.yaml
- .yarn/versions/e48d455e.yml
- packages/hdkey/index.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/566)
> ci: minor ci change

- .yarn/versions/1b9866b2.yml
- packages/dapp-cross-space/src/index.css
- packages/dapp-cross-space/src/manage/index.tsx
- packages/dapp-cross-space/src/manage/useConflux/ConfluxManage.ts
- packages/dapp-cross-space/src/manage/useConflux/index.ts
- packages/dapp-cross-space/src/manage/useConflux/useCrossSpaceContract.tsx
- packages/dapp-cross-space/src/manage/useFluent/FluentManage.ts
- packages/dapp-cross-space/src/pages/Evm2Main/index.tsx
- packages/dapp-cross-space/src/pages/Main2Evm/index.tsx
- packages/dapp-cross-space/src/pages/Nav/index.tsx
- packages/dapp-cross-space/types/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/571)
> fix: dapp-cross-space change chainId

- .yarn/versions/2cbe2341.yml
- packages/dapp-cross-space/src/manage/index.tsx
- packages/dapp-cross-space/src/manage/useEvm/EvmManage.ts
- packages/dapp-cross-space/src/manage/useEvm/index.tsx
- packages/dapp-cross-space/src/manage/useFluent/FluentManage.ts
- packages/dapp-cross-space/src/pages/Main2Evm/index.tsx
- packages/dapp-cross-space/src/pages/Nav/index.tsx
- packages/dapp-cross-space/src/pages/index.tsx
- packages/dapp-cross-space/types/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/575)
> feat: Cross-space-dapp add network check

- .yarn/versions/5c1958c1.yml
- packages/conflux-tx-error/index.js
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.test.js
- packages/webextension/notifications.js
add some unit tests for handle unfinished tx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/568)
> refactor: wording for handle unfinished tx

- .yarn/versions/ca20ee3a.yml
- packages/background/src/index.integration.test.js
- packages/rpcs/wallet_deleteNetwork/index.js
PORTAL-2409
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/573)
> feat: select next network when delete current one

- .github/mergify.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/579)
> ci: more mergify config

- .yarn/versions/4d3cce70.yml
- packages/background/src/index.integration.test.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/581)
> fix: robust integration test

- .github/workflows/publish-npm-package.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/582)
> ci: speed up npm release

- .yarn/versions/3a759c20.yml
- .yarn/versions/f1e56cad.yml
- packages/base32-address/index.js
- packages/base32-address/package.json
- packages/contract-method-name/constance.js
- packages/contract-method-name/package.json
- packages/tx-history-checker/index.js
- packages/tx-history-checker/package.json
- packages/ui/shorten-address/index.js
- packages/ui/shorten-address/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/595)
> chore: extract netId to consts

- .github/workflows/pre-release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/600)
> ci: fix pre release

- .yarn/versions/c1c098ef.yml
- packages/dapp-cross-space/src/pages/Evm2Main/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/610)
> style: dpp-cross-space text

- .yarn/versions/ff4c3a45.yml
- packages/popup/src/pages/History/index.js
fix PORTAL-2332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/613)
> fix: fix PORTAL-2332

- .yarn/versions/e67509bf.yml
- packages/dapp-cross-space/src/pages/Evm2Main/index.tsx
- packages/popup/src/pages/History/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/615)
> fix: history list not show bug

- .yarn/versions/f04d6bbf.yml
- packages/popup/src/components/TitleNav.js
change title nav button click event
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/620)
> test: change title nav button click event 

- .yarn/versions/1e6c91bc.yml
- packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/622)
> fix: style check

- .github/mergify.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/624)
> ci: better mergify config

- .github/scripts/getPreReleaseNumber.js
- .github/workflows/pre-release.yaml
- .github/workflows/prod-release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/625)
> ci: fix prod release changelog

- .github/mergify.yml
- .github/release-drafter-pre.yml
- .github/release-drafter-prod.yml
- .github/release-drafter.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/628)
> ci: fix mergify conf for prod release

- .env
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/630)
> chore: bump version in env

- .yarn/versions/22a0e651.yml
- packages/popup/src/hooks/index.js
- packages/popup/src/hooks/useApi.js
- packages/popup/src/pages/CurrentSeed/index.js
- packages/popup/src/pages/Home/components/Setting.js
- packages/popup/src/pages/SelectCreateType/index.js
- packages/popup/src/pages/Unlock/index.js
- packages/popup/src/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/631)
> feat: PORTAL-2263

- .yarn/versions/337c6a97.yml
- packages/popup/src/pages/ConnectSite/index.js
fix PORTAL-2342
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/634)
> fix: fix PORTAL-2342

- .yarn/versions/47faf16d.yml
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.test.js
- packages/transducers/index.js
add unit test for wallet_handleUnfinishedCFXTx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/626)
> fix: potensial memory leak in tx status tracker

- .yarn/versions/08b0b952.yml
- packages/dapp-cross-space/src/pages/Nav/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/639)
> fix: dapp-cross-space some time add button not show

- .yarn/versions/8cc20bae.yml
- packages/dapp-cross-space/src/manage/useConflux/ConfluxManage.ts
- packages/dapp-cross-space/src/manage/useEvm/EvmManage.ts
- packages/dapp-cross-space/src/manage/useFluent/FluentManage.ts
- packages/dapp-cross-space/src/pages/Connect/index.tsx
- packages/dapp-cross-space/src/pages/Evm2Main/index.tsx
- packages/dapp-cross-space/src/pages/Main2Evm/index.tsx
- packages/dapp-cross-space/src/pages/Nav/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/641)
> fix: change network config, add id for test.

- .github/mergify.old.yml
- .github/release-drafter-prod.yml
- .github/workflows/pre-release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/632)
> ci: fix pre-release workflow

- .github/mergify.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/644)
> ci: auto update pr with merge

- .github/mergify.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/645)
> ci: fix mergify queue

- .github/mergify.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/646)
> ci: fix mergify

- .yarn/versions/5f1ba0d8.yml
- packages/popup/src/App.js
- packages/popup/src/pages/AccountManagement/components/AccountItem.js
- packages/popup/src/pages/History/components/HistoryItem.js
- packages/popup/src/pages/History/index.js
- packages/popup/src/pages/SelectCreateType/components/CreateTypeItem.js
- packages/popup/src/pages/SelectCreateType/index.js
- scripts/tailwind.config.js
fix ui bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/647)
> fix: fix ui bug

- .yarn/versions/621d20b3.yml
- packages/rpcs/wallet_refetchBalance/index.js
- packages/rpcs/wallet_refetchBalance/package.json
- yarn.lock
PORTAL-2504
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/643)
> fix: refetch balance won't return error

- .yarn/versions/b57f226d.yml
- packages/popup/src/hooks/useApi.js
- packages/popup/src/pages/AccountManagement/components/AccountItem.js
1.PORTAL-2516
2.PORTAL-2506
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/650)
> fix: fix bug

- .yarn/versions/3b8cf433.yml
- packages/dapp-cross-space/src/index.css
- packages/dapp-cross-space/src/pages/Evm2Main/index.tsx
- packages/dapp-cross-space/src/pages/Main2Evm/index.tsx
- packages/dapp-cross-space/src/pages/Nav/index.css
- packages/dapp-cross-space/src/pages/Nav/index.tsx
- packages/dapp-cross-space/src/pages/index.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/651)
> style: dapp-cross-space

- .github/workflows/push-check.yaml
- jest.config.js
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/654)
> ci: split test folder to unittest and integration

- .yarn/versions/e22dd5a2.yml
- packages/browser-extension/_locales/zh/messages.json
- packages/browser-extension/manifest.json.mustache
- scripts/before_all.js
PORTAL-2492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/653)
> feat: add zh/message.json

- .yarn/versions/7ab70f7a.yml
- packages/popup/src/locales/en.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/656)
> fix: PORTAL-2499

- .yarn/versions/b0b0a3a4.yml
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/rpcs/wallet_setAppCurrentNetwork/index.js
- packages/rpcs/wallet_setCurrentNetwork/index.js
1. send connect event on network change
2. send accountsChanged event when switch from/to cfx network
PORTAL-2548
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/659)
> fix: provider event tweak

- .yarn/versions/98c37869.yml
- packages/dapp-cross-space/src/pages/Evm2Main/index.tsx
- packages/dapp-cross-space/src/pages/Main2Evm/index.tsx
- packages/dapp-cross-space/src/pages/Nav/index.tsx
- packages/dapp-cross-space/src/pages/index.tsx
- packages/dapp-cross-space/types/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/660)
> style: dapp-cross-space text

- .yarn/versions/28de4b9c.yml
- packages/popup/src/pages/AccountManagement/components/AccountItem.js
- packages/popup/src/pages/AccountManagement/components/GroupItem.js
- packages/popup/src/pages/SelectCreateType/index.js
fix PORTAL-2562
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/663)
> fix: fix PORTAL-2562

- .yarn/versions/d8576949.yml
- packages/background/src/index.integration.test.js
- packages/rpcs/wallet_addNetwork/index.js
- packages/rpcs/wallet_updateNetwork/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/673)
> fix: update network

- .yarn/versions/c8fa67a7.yml
- packages/popup/src/App.js
- packages/popup/src/index.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/679)
> fix: window open popup scrollbar bug

- .gitignore
- .yarn/versions/568a9ec6.yml
- packages/test-helpers/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/682)
> test: test with new version fullnode

- .yarn/versions/9e65e828.yml
- packages/dapp-cross-space/src/components/ShortenAddress/index.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/684)
> style: zIndex of tips

- .yarn/versions/9e65e828.yml
- packages/dapp-cross-space/src/components/ShortenAddress/index.css
- packages/dapp-cross-space/src/manage/useConflux/ConfluxManage.ts
- packages/dapp-cross-space/src/pages/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/686)
> Dapp cross space

- .yarn/versions/f5a3f5eb.yml
- packages/dapp-cross-space/src/manage/useFluent/FluentManage.ts
- packages/dapp-cross-space/types/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/688)
> fix: dapp-cross-space connect bug

- .yarn/versions/fa8cd1a6.yml
- packages/popup/src/constants/index.js
- packages/popup/src/locales/en.js
- packages/popup/src/locales/zh.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/690)
> fix: pwd max length to 128 in frontend

- .yarn/versions/b17bf6d5.yml
- packages/dapp-cross-space/src/manage/useConflux/ConfluxManage.ts
- packages/dapp-cross-space/src/manage/useEvm/EvmManage.ts
- packages/dapp-cross-space/src/pages/Evm2Main/index.tsx
- packages/dapp-cross-space/src/pages/Main2Evm/index.tsx
- packages/dapp-cross-space/src/pages/Nav/index.tsx
- packages/dapp-cross-space/src/pages/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/692)
> style: space-chain name

- .yarn/versions/44b3a65d.yml
- packages/dapp-cross-space/src/main.tsx
- packages/dapp-cross-space/src/manage/useConflux/ConfluxManage.ts
- packages/dapp-cross-space/src/manage/useFluent/FluentManage.ts
- packages/dapp-cross-space/src/pages/Evm2Main/index.tsx
- packages/dapp-cross-space/src/pages/Main2Evm/index.tsx
- packages/dapp-cross-space/src/pages/Nav/index.tsx
- packages/dapp-cross-space/src/pages/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/694)
> fix: dapp-cross-space text

- .yarn/versions/ce8a9804.yml
- packages/dapp-cross-space/src/pages/Nav/index.tsx
- packages/dapp-cross-space/src/pages/index.tsx
- packages/popup/src/pages/Home/components/CrossSpaceButton.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/696)
> feat: cross-space dapp open from fluent always in Core-to-eSpace page

- .yarn/versions/f8a9add1.yml
- packages/rpcs/wallet_addNetwork/index.js
PORTAL-2614 able to remove explorer url
PORTAL-2613 error when update current network name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/701)
> fix: update network fix

- .yarn/versions/b46dda05.yml
- packages/popup/src/pages/NetworkDetail/index.js
add symbol placeholder when editing network
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/706)
> fix: add symbol placeholder when editing network

- .yarn/versions/4509f7f0.yml
- packages/popup/package.json
- packages/popup/src/components/DappFooter.js
- packages/popup/src/constants/index.js
- packages/popup/src/locales/en.js
- packages/popup/src/locales/zh.js
- packages/popup/src/pages/ConfirmTransaction/components/HwTransactionResult.js
- packages/popup/src/pages/ConfirmTransaction/index.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/705)
> feat: tx send error display

- .yarn/versions/24f5f08d.yml
- packages/rpcs/wallet_registerSiteMetadata/index.js
- packages/rpcs/wallet_setPreferences/index.js
- packages/rpcs/wallet_setPreferences/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/709)
> fix: post provider api change event to content script

- .yarn/versions/b0aa54a8.yml
- packages/extension-runtime/background.js
- packages/extension-runtime/package.json
- scripts/before_all.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/711)
> fix: firefox postMessage

- .github/workflows/prod-release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/715)
> ci: fix prod release commitish

- .yarn/versions/2231a8d3.yml
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/ui/provider-api/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/726)
> fix: compatible provider api (#724)

- .github/workflows/prod-release.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/728)
> ci: prod release for hotfix

- .yarn/versions/1108517f.yml
- packages/ledger/conflux.js
- packages/ledger/const.js
- packages/ledger/ethereum.js
- packages/ledger/index.js
- packages/ledger/package.json
- yarn.lock
1. support Ethereum on ledger
- `getAddress`
- `signTransaction`
- `signPersonalMessage`
- `getAppConfiguration`
- `getAddressList`
2. add signPersonalMessage API to Conflux on the ledger
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/723)
> feat: support ethereum on ledger

- .yarn/versions/7e6ca113.yml
- packages/rpc-engine/middlewares/validate-rpc-data.js
PORTAL-2655
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/740)
> feat: eth typed sign under conflux network

- .yarn/versions/071b9105.yml
- packages/db/src/main/cfxjs/db/queries.cljs
PORTAL-2654
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/741)
> feat(db): query address by vault type

- .gitignore
- bb.edn
- scripts/x/nrepl.clj
- scripts/x/shadow.clj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/747)
> chore: use babashka task for faster dev workflow

- .yarn/versions/a14cea7e.yml
- packages/background/src/index.integration.test.js
- packages/consts/index.js
- packages/db/src/main/cfxjs/db/migrations/core.cljs
- packages/db/src/main/cfxjs/db/migrations/m5.cljs
- packages/db/src/main/cfxjs/db/migutil.cljs
- packages/rpcs/wallet_setPreferences/index.js
- packages/test-helpers/package.json
- yarn.lock
1. change network name
2. use v2.0.0 conflux-rust to run integration test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/751)
> feat: get ready for hydra

- .yarn/versions/ab459302.yml
- packages/background/src/index.integration.test.js
- packages/background/src/rpc-engine-opts.js
- packages/estimate-tx/eth.js
- packages/rpcs/cfx_gasPrice/index.js
- packages/rpcs/eth_blockNumber/index.js
- packages/rpcs/eth_estimateGas/index.js
- packages/rpcs/eth_gasPrice/index.js
- packages/rpcs/eth_getTransactionCount/index.js
- packages/rpcs/eth_signTransaction/index.js
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.test.js
- packages/rpcs/wallet_handleUnfinishedETHTx/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/756)
> fix: bugs in rpc spec, pending tx handler

- .github/release-drafter-pre.yml
- .github/release-drafter-prod.yml
- .github/release-drafter.yml
- .github/workflows/publish-npm-package.yaml
- .yarn/versions/d3ed8daf.yml
- packages/rpcs/wallet_getPreferences/index.js
- packages/webextension/popup.js
also allow popup/internal get prefs when locked
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/763)
> fix: can't open second popup after unlock

- .yarn/versions/3e3d85b5.yml
- packages/ledger/ethereum.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/762)
> docs: fix doc build

- .yarn/versions/3b6cd09f.yml
- packages/dapp-cross-space/package.json
- packages/dapp-cross-space/src/pages/Nav/index.tsx
- packages/dapp-cross-space/vite.config.ts
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/761)
> feat: dapp-cross-space add chain to metamask button in Tethys

- .github/workflows/publish-npm-package.yaml
- scripts/any-packages-version-changed.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/769)
> ci: don't run useless npm publish

- .github/workflows/push-check.yaml
- .yarn/versions/2231a8d3.yml
- scripts/any-packages-version-changed.sh
debug any-packages-version-changed
merge main to dev
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/772)
> ci: remove build-storybook

- scripts/any-packages-version-changed.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/774)
> ci: wrong script logic

- .yarn/versions/81d7ddff.yml
- packages/background/src/index.integration.test.js
- packages/consts/index.js
- packages/rpcs/wallet_addHdPath/index.js
- packages/rpcs/wallet_addNetwork/index.js
bug fix and integration test for:
- `wallet_addNetwork`
- `wallet_addHdPath`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/777)
> feat: integration test and bug fix

- .yarn/versions/7d8f3190.yml
- packages/popup/src/components/GasFee.js
- packages/popup/src/components/NetworkContent.js
- packages/popup/src/hooks/useApi.js
- packages/popup/src/pages/DappSwitchNetwork/index.js
- packages/popup/src/pages/EditGasFee/index.js
- packages/popup/src/pages/History/components/HistoryItem.js
- packages/popup/src/pages/NetworkDetail/index.js
- packages/popup/src/pages/RequestSignature/index.js
PORTAL-2667
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/787)
> feat: add eth network

- .yarn/versions/c0001082.yml
- packages/popup/src/components/SearchAccount.js
- packages/popup/src/pages/AccountManagement/index.js
- packages/popup/src/utils/index.js
PORTAL-2716
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/789)
> fix: fix PORTAL-2716

- .yarn/versions/03f98a7b.yml
- packages/webextension/tab.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/795)
> fix: tabs(PORTAL-2055)

- .yarn/versions/5083dc08.yml
- packages/webextension/popup.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/797)
> fix: PORTAL-2639

- .yarn/versions/c1148b3e.yml
- packages/popup/src/locales/en.js
- packages/popup/src/locales/fr.js
- packages/popup/src/locales/index.js
- packages/popup/src/locales/zh.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/801)
> feat: add French localization

- .yarn/versions/bbe6d2a8.yml
- packages/rpcs/wallet_dbQuery/index.js
temporary solution
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/804)
> fix: bug(PORTAL-2746)

- .yarn/versions/bbe6d2a8.yml
- packages/rpcs/wallet_dbQuery/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/807)
> fix: reset code

- .yarn/versions/bbe6d2a8.yml
- packages/rpcs/wallet_dbQuery/index.js
1. reset the query code
2. hide the error message and return [] for `query_address`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/809)
> fix: reset the query code

- .env
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/813)
> chore: update version

- .yarn/versions/dec1e0e1.yml
- packages/single-call-balance-tracker/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/821)
> feat: add balance checker for espace

- .yarn/versions/02e63b00.yml
- packages/inpage/setup-inpage-provider.js
- packages/inpage/take-over-portal.js
- scripts/x/shadow.clj
use Object.defineProperty writable: false
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/830)
> fix: setup inpage provider

- .yarn/versions/c0001082.yml
- packages/popup/src/components/NumberInput.js
PORTAL-2820
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/843)
> fix: fix PORTAL-2820

- .yarn/versions/65c307c1.yml
- packages/ui/data-format/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/845)
> fix: remove data-format unsused package

- .yarn/versions/c0001082.yml
- packages/popup/src/components/NumberInput.js
- packages/popup/src/pages/History/components/ResendTransaction.js
PORTAL-2818
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/847)
> fix: fix PORTAL-2818

- .yarn/versions/9893f6aa.yml
- packages/background/package.json
- packages/background/src/rpc-engine-opts.js
- yarn.lock
PORTAL-2848
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/867)
> fix: cfx_getBlockByEpochNumber

- .yarn/versions/5083dc08.yml
- packages/popup/src/components/NumberInput.js
- packages/popup/src/pages/EditGasFee/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/875)
> fix: decimals = 0

- .yarn/versions/79284a21.yml
- packages/background/package.json
- packages/background/src/rpc-engine-opts.js
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/rpcs/eth_signTransaction/index.js
- packages/rpcs/eth_signTxWithLedgerNanoS/README.md
- packages/rpcs/eth_signTxWithLedgerNanoS/index.js
- packages/rpcs/eth_signTxWithLedgerNanoS/package.json
- packages/rpcs/wallet_createAccount/index.js
- packages/rpcs/wallet_createAddress/doc.js
- packages/rpcs/wallet_createAddress/index.js
- packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js
- packages/signature/index.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/878)
> feat: ledger support for eth network

- .yarn/versions/11178e45.yml
- packages/rpcs/wallet_createAddress/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/880)
> fix: addr by network type in wallet_createAddress

- .yarn/versions/aee5622d.yml
- packages/background/src/index.integration.test.js
- packages/rpcs/cfx_signTransaction/index.js
- packages/rpcs/eth_signTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/882)
> fix: signtx get addr params

- .yarn/versions/45bb7ad8.yml
- packages/account/index.js
PORTAL-2882
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/884)
> feat: add checksum fn

- .yarn/versions/e40d77d3.yml
- packages/popup/src/components/AccountDisplay.js
- packages/popup/src/locales/en.js
- packages/popup/src/locales/fr.js
- packages/popup/src/locales/ru.js
- packages/popup/src/locales/zh.js
- packages/popup/src/pages/AdvancedSettings/index.js
- packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
- packages/popup/src/pages/ConnectSite/index.js
- packages/popup/src/pages/History/components/HistoryItem.js
- packages/popup/src/pages/Home/components/CurrentAccount.js
- packages/popup/src/pages/SendTransaction/index.js
- packages/popup/src/utils/index.js
1.add scroll bar in connect wallet
2.PORTAL-2881
3.change advanced settings ui
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/890)
> feat: add eip55

- .yarn/versions/5083dc08.yml
- packages/popup/src/components/TransactionResult.js
- packages/popup/src/locales/en.js
- packages/popup/src/locales/fr.js
- packages/popup/src/locales/ru.js
- packages/popup/src/locales/zh.js
- packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
- packages/popup/src/pages/ConfirmTransaction/index.js
- packages/popup/src/pages/History/components/ResendTransaction.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/893)
> feat: send transaction error modal

- .yarn/versions/e40d77d3.yml
- packages/popup/src/components/DappFooter.js
- packages/popup/src/components/NetworkContent.js
- packages/popup/src/hooks/index.js
- packages/popup/src/locales/en.js
- packages/popup/src/locales/fr.js
- packages/popup/src/locales/ru.js
- packages/popup/src/locales/zh.js
- packages/popup/src/pages/ConfirmTransaction/index.js
- packages/popup/src/pages/ConnectSite/index.js
1.PORTAL-2834
2.add error message in dApp pages
3.PORTAL-2914
4.PORTAL-2900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/898)
> feat: change ui

- .yarn/versions/3b6cd09f.yml
- .yarn/versions/e133ff03.yml
- packages/popup/src/index.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/903)
> fix: PORTAL-2934

- .yarn/versions/0b491a12.yml
- packages/json-rpc-error/index.js
- packages/rpcs/wallet_switchEthereumChain/index.js
PORTAL-2925
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/910)
> fix: 4902 error when can't find target of switchXChain

- .yarn/versions/bdb1d5ed.yml
- packages/safe-event-emiter/index.js
fix typo
PORTAL-2862
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/909)
> feat(provider): support removeAllListeners

- .github/mergify.yml
- .yarn/versions/a48238dd.yml
- packages/inpage/setup-inpage-provider.js
- packages/inpage/setup-inpage-provider.test.js
PORTAL-2918
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/915)
> feat: set(not takeover) window.ethereum by default

- .yarn/versions/c572adc3.yml
- packages/ledger/conflux.js
- packages/ledger/ethereum.js
modify the way of importing package
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/918)
> fix: import way(PORTAL-3003)

- .yarn/versions/a48238dd.yml
- .yarn/versions/bb62214a.yml
- packages/inpage/package.json
- packages/popup/src/components/CopyButton.js
- packages/popup/src/components/NetworkContent.js
- packages/popup/src/hooks/index.js
- packages/popup/src/locales/en.js
- packages/popup/src/pages/Home/components/AccountList.js
- packages/popup/src/pages/Home/components/CurrentAccount.js
- packages/popup/src/pages/Home/components/useAddressAnimation.js
- scripts/tailwind.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/921)
> fix: fix some bugs and PORTAL-2151

- .yarn/versions/4a7c3ac3.yml
- packages/ledger/package.json
- yarn.lock
According to the [esbuild doc](https://esbuild.github.io/api/#main-fields), add a `module` field to `hw-app-conflux` package  to fix this issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/942)
> fix: can not import account through ledger

- .yarn/versions/630289e4.yml
- packages/rpcs/wallet_createAccount/index.js
- packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js
PORTAL-2943
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/933)
> fix: don't select newly created acc

- .yarn/versions/1fd08d1d.yml
- packages/popup/src/components/IdentityPanel.js
- packages/popup/src/locales/en.js
- packages/popup/src/locales/fr.js
- packages/popup/src/locales/ru.js
- packages/popup/src/locales/zh.js
- packages/popup/src/pages/AccountManagement/index.js
- packages/popup/src/pages/ExportPrivateKey/index.js
- packages/popup/src/stores/index.js
PORTAL-3010
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/948)
> feat: PORTAL-3010

- .yarn/versions/fedf6237.yml
- packages/background/src/init-db.js
- packages/db/src/main/cfxjs/db/migrations/m6.cljs
- packages/ethereum-tx-error/index.js
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
- packages/rpcs/wallet_handleUnfinishedETHTx/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/946)
> fix: tx error on espace

- .yarn/versions/a138b2f5.yml
- packages/background/src/init-db.js
- packages/db/src/main/cfxjs/db/migrations/m6.cljs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/953)
> feat: add espace tokenlist

- .yarn/versions/ff7c2f18.yml
- packages/consts/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/955)
> fix: eSpace testnet name

- .yarn/versions/5d69660f.yml
- packages/db/src/main/cfxjs/db/queries.cljs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/966)
> docs: add comments to upsert-token-list

- .yarn/versions/8ec7ec0c.yml
- packages/rpcs/wallet_sendTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/974)
> fix: duptx stuck auth req

- .yarn/versions/4f6fbb0a.yml
- packages/popup/src/pages/Home/components/CrossSpaceButton.js
add hash in cross space url
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/976)
> fix: fix cross space link

- .yarn/versions/d6953091.yml
- packages/popup/src/pages/EditAllowance/index.js
fix approve input style
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/978)
> fix: fix approve input style

- .yarn/versions/eb57f18d.yml
- bb.edn
- packages/db/src/main/cfxjs/db/queries.cljs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/979)
> fix: failed to check dapp's currentAccount

- .yarn/versions/edab3a5a.yml
- packages/popup/src/hooks/index.js
fix wrong contract method name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/982)
> fix: fix wrong contract method name

- .yarn/versions/1afa36bf.yml
- packages/safe-event-emiter/index.js
1. fix removeAllListener
2. fix on/off return value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/984)
> fix: provider event emitter api

- .yarn/versions/1dadbbcf.yml
- packages/ethereum-tx-error/index.js
- packages/rpcs/wallet_handleUnfinishedETHTx/index.js
PORTAL-3066
based on metamask's pending tx tracker
https://github.com/MetaMask/metamask-extension/blob/582f6168f9860a1f7a5dbf950b53d8b8c471312d/app/scripts/controllers/transactions/pending-tx-tracker.js#L95
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/986)
> fix: resend mark tx error

- .yarn/versions/647451f7.yml
- packages/background/src/init-db.js
- packages/db/src/main/cfxjs/db/migrations/m6.cljs
- packages/estimate-tx/eth.js
- packages/popup/src/hooks/index.js
- packages/popup/src/hooks/useApi.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/988)
> feat: add gasBuffer support

- .yarn/versions/e3ccd685.yml
- packages/popup/package.json
- packages/popup/src/components/TransactionResult.js
- packages/popup/src/locales/en.js
- packages/popup/src/locales/fr.js
- packages/popup/src/locales/ru.js
- packages/popup/src/locales/zh.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/990)
> feat: eth tx error

- .yarn/versions/e3ccd685.yml
- packages/popup/src/components/TransactionResult.js
- packages/popup/src/pages/ConfirmTransaction/index.js
- packages/popup/src/pages/History/components/ResendTransaction.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/992)
> fix: send error

- .env
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/995)
> chore: next version 2.1.0

- .yarn/versions/ec07ebaf.yml
- bb.edn
- packages/background/src/index.js
add docs to background/index.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/996)
> fix: cleanup wallet_importAll data

- .yarn/versions/f75ae5c7.yml
- packages/rpcs/cfx_signTransaction/index.js
- packages/rpcs/eth_signTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/998)
> refactor: more readable eth_signTransaction

- .yarn/versions/12c9230b.yml
- packages/cache-rpc/index.js
- packages/rpcs/cfx_chainId/index.js
- packages/rpcs/eth_chainId/index.js
- packages/rpcs/net_version/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/997)
> fix: docs about cache

- .yarn/versions/058dfbf3.yml
- packages/sentry/computeDefaultOptions.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1002)
> fix: sentry release

- .yarn/versions/2cb39ae4.yml
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
- packages/rpcs/wallet_handleUnfinishedETHTx/index.js
better review commit by commit
fix: wrong tx error type
fix: fail resend tx with err replacement gas low
feat: set same nonce pending tx failed
feat: speed tx status detection
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1011)
> feat: improve/fix pending tx handler

- .yarn/versions/6016f301.yml
- bb.edn
- deps.edn
- packages/background/package.json
- packages/background/src/rpc-engine-opts.js
- packages/db/src/main/cfxjs/db/datascript/db.cljc
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/rpcs/wallet_deleteAccount/README.md
- packages/rpcs/wallet_deleteAccount/index.js
- packages/rpcs/wallet_deleteAccount/package.json
- yarn.lock
PORTAL-3087
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1016)
> feat: add wallet_deleteAccount

- .yarn/versions/a36d1b30.yml
- deps.edn
- packages/background/src/db-schema.js
- packages/db/src/main/cfxjs/db/core.cljs
- packages/db/src/main/cfxjs/db/queries.cljs
- scripts/cljs_devtool.clj
- scripts/cljs_devtool.cljs
- shadow-cljs.edn
1. refactor/document `upsert-balance` `upsert-token-list`
2. add new attribute `:address/antiToken`
3. add token to `:address/antiToken` in `retract-address-token` when token is in tokenlist
4. remove token from `:address/antiToken` in `add-token-to-addr`
5. avoid token in `:address/antiToken` get into `:address/token` in `upsert-balance`
PORTAL-1569
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1019)
> feat: unwatch asset

- .yarn/versions/15b77f96.yml
- packages/background/src/index.integration.test.js
- packages/consts/index.js
- packages/db/src/main/cfxjs/db/migrations/core.cljs
- packages/db/src/main/cfxjs/db/migrations/m9.cljs
PORTAL-3081
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1028)
> fix: conflux core mainnet name

- .yarn/versions/e3ccd685.yml
- packages/popup/src/hooks/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1032)
> fix: PORTAL-3095

- .yarn/versions/e3ccd685.yml
- packages/popup/src/pages/SendTransaction/components/TokenAndAmount.js
- packages/popup/src/pages/SendTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1033)
> fix: max bug

- .yarn/versions/2e2868b8.yml
- packages/db/src/main/cfxjs/db/migrations/core.cljs
- packages/db/src/main/cfxjs/db/migrations/m10.cljs
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/db/src/main/cfxjs/db/schema.cljc
bug: can't remove token which
1. linked to more than one address
2. not in tokenlist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1044)
> fix: retract token

- .yarn/versions/4b51fadc.yml
- packages/popup/src/hooks/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1054)
> fix: estimate error

- .yarn/versions/8e01d788.yml
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/rpcs/wallet_setAppCurrentNetwork/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1056)
> fix: hw account network switch handler

- .yarn/versions/73351114.yml
- packages/popup/src/hooks/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1061)
> fix: PORTAL-3110

- .yarn/versions/52d7f5bb.yml
- packages/popup/src/locales/ru.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1059)
> Update Russian localization for v2.0.0

- .yarn/versions/1ee3b409.yml
- packages/rpcs/wallet_updateAccount/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1067)
> fix: wrong upt acc logic

- .yarn/versions/bf35f30c.yml
- packages/db/src/main/cfxjs/db/queries.cljs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1072)
> fix: isLastNoneHWAccount

- .yarn/versions/10c95ddf.yml
- packages/popup/src/locales/fr.js
Based on #1068.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1074)
> feat: update French localization

- .yarn/versions/43b5dab9.yml
- packages/rpcs/wallet_afterUnlock/index.js
PORTAL-3104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1069)
> fix: eth hw account in fillMissingAccountAddress

- .yarn/versions/be7fc44e.yml
- packages/db/src/main/cfxjs/db/queries.cljs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1066)
> refactor: refetchBalance

- .yarn/versions/d9c983b1.yml
- packages/rpcs/wallet_refetchBalance/index.js
PORTAL-3155
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1081)
> fix: upsert balance

- .yarn/versions/383068bf.yml
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/rpcs/wallet_createAddress/index.js
PORTAL-3150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1080)
> fix: hw account createAddress on new network

- .yarn/versions/f5f7aa73.yml
- packages/rpcs/wallet_afterUnlock/index.js
PORTAL-3104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1087)
> fix: cfxOnly bug in fillMissingAccountAddress

- .yarn/versions/5bccae0c.yml
- packages/rpcs/wallet_addPendingUserAuthRequest/index.js
when more than one auth reqs has
1. same site id (unauthed) or same app id (authed)
2. has same request payload (method, params)
3. the first req is not confirmed by user
skip the rest reqs
PORTAL-3159
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1085)
> fix: skip dup pending req

- .yarn/versions/dd57e5b8.yml
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/rpcs/cfx_requestAccounts/index.js
- packages/rpcs/eth_requestAccounts/index.js
- packages/rpcs/wallet_requestPermissions/index.js
- packages/rpcs/wallet_switchEthereumChain/index.js
- packages/wallet-permission/docs.js
- packages/wallet-permission/index.js
- packages/wallet-permission/permissions.js
1. Based on mm's doc and behavior permission params must include at least one of
- cfx_accounts
- eth_accounts
- wallet_accounts
2. notify site accountsChanged
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1090)
> fix: wallet_requestPermissions

- .yarn/versions/b6367ad2.yml
- packages/popup/src/locales/ru.js
- packages/popup/src/locales/uk.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1093)
> feat: update ru and uk localizations

- .yarn/versions/9da3deb3.yml
- packages/db/src/main/cfxjs/db/queries.cljs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1099)
> fix: add total to walletdb_queryRecentInterestingAddress

- .yarn/versions/06d8b724.yml
- packages/background/src/db-schema.js
- packages/db/src/main/cfxjs/db/migrations/m11.cljs
- packages/db/src/main/cfxjs/db/queries.cljs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1101)
> fix: add total in queryMemo

- .yarn/versions/59821ef6.yml
- packages/popup/src/locales/en.js
- packages/popup/src/locales/fr.js
- packages/popup/src/locales/ru.js
- packages/popup/src/locales/uk.js
- packages/popup/src/locales/zh.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1104)
> fix: PORTAL-3158

- .yarn/versions/5fa25f1b.yml
- packages/contract-method-name/cfx-name.js
- packages/contract-method-name/index.js
- packages/json-rpc-error/index.js
- packages/rpc-engine/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1103)
> fix: UnrecognizedChainId error

- .yarn/versions/dfdec735.yml
- packages/rpcs/wallet_getPermissions/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1108)
> fix: don't return crossNetwork perm with network prefix

- .yarn/versions/59821ef6.yml
- packages/popup/src/components/DappFooter.js
- packages/popup/src/components/DappProgressHeader.js
- packages/popup/src/constants/index.js
- packages/popup/src/constants/rpcMethods.js
- packages/popup/src/locales/en.js
- packages/popup/src/locales/fr.js
- packages/popup/src/locales/ru.js
- packages/popup/src/locales/uk.js
- packages/popup/src/locales/zh.js
- packages/popup/src/pages/ConnectSite/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1106)
> feat: PORTAL-3121

- .yarn/versions/1497ac08.yml
- packages/popup/src/locales/zh.js
add zh copy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1114)
> feat: add zh copy

- .yarn/versions/7c95be41.yml
- packages/db/src/main/cfxjs/db/queries.cljs
PORTAL-3200
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1118)
> feat: memo query support fuzzy addr

- .yarn/versions/7cd77f13.yml
- packages/db/src/main/cfxjs/db/queries.cljs
PORTAL-3224
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1126)
> fix: recent interesting addr query performance

- .yarn/versions/b39e06f9.yml
- packages/db/src/main/cfxjs/db/queries.cljs
PORTAL-3174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1124)
> feat: filter same nonce tx

- .yarn/versions/f4f43759.yml
- packages/db/src/main/cfxjs/db/queries.cljs
PORTAL-3244
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1133)
> fix: fuzzy search assets error

- .yarn/versions/6574dc85.yml
- packages/db/src/main/cfxjs/db/queries.cljs
PORTAL-3256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1135)
> fix: recent dup addr

- .yarn/versions/f0dca868.yml
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
PORTAL-3179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1139)
> fix: nonce too stale when resend same as success

- .yarn/versions/891d0785.yml
- packages/popup/src/components/ContactItem.js
- packages/popup/src/pages/AddressBook/components/Account.js
- packages/popup/src/pages/AddressBook/components/Contact.js
- packages/popup/src/pages/AddressBook/components/Recent.js
- packages/popup/src/pages/AddressBook/index.js
- scripts/tailwind.config.js
1.PORTAL-3255
2.PORTAL-3243
3.change style
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1138)
> fix: fix PORTAL-3255

- .yarn/versions/9667ade9.yml
- packages/db/src/main/cfxjs/db/queries.cljs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1144)
> fix: tx list typo

- .yarn/versions/33345fbe.yml
- packages/db/src/main/cfxjs/db/queries.cljs
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.test.js
- packages/rpcs/wallet_handleUnfinishedETHTx/index.js
PORTAL-3074
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1147)
> fix: double check skipped tx

- .yarn/versions/f34f39b3.yml
- packages/popup/src/components/Avatar.js
- packages/popup/src/pages/AccountManagement/index.js
PORTAL-3281
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1151)
> fix: fix PORTAL-3281

- .dir-locals.el
- .env
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1155)
> chore: next version 2.3.0

- .yarn/versions/80c5db4e.yml
- packages/popup/src/pages/ConnectSite/index.js
PORTAL-3297
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1163)
> fix: fix PORTAL-3297

- .yarn/versions/a3b07ef8.yml
- packages/popup/src/components/AccountItem.js
- packages/popup/src/components/Avatar.js
- packages/popup/src/pages/AccountManagement/index.js
PORTAL-3284
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1165)
> feat: finish PORTAL-3284

- .yarn/versions/1e56c583.yml
- packages/conflux-tx-error/index.js
- packages/ethereum-tx-error/index.js
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
- packages/rpcs/wallet_handleUnfinishedETHTx/index.js
- packages/rpcs/wallet_refetchTxList/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1173)
> feat: data and error from receipt

- .yarn/versions/f1e0ecca.yml
- packages/rpc-engine/middlewares/call-rpc.js
- packages/rpc-engine/src/permissions.js
- packages/rpcs/wallet_addEthereumChain/index.js
- packages/rpcs/wallet_validate20Token/index.js
PORTAL-3083
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1176)
> fix: call addEthereumChain/addConfluxChain without connect

- .yarn/versions/ff715fc5.yml
- packages/db/src/main/cfxjs/db/queries.cljs
PORTAL-3301
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1175)
> feat: add queryTx by hash

- .yarn/versions/ba68818e.yml
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
- packages/rpcs/wallet_handleUnfinishedETHTx/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1183)
> feat: show execute error in tx failed notification

- .yarn/versions/5f1df731.yml
- packages/rpcs/cfx_signTransaction/index.js
- packages/rpcs/eth_signTransaction/index.js
- packages/rpcs/wallet_sendTransaction/index.js
PORTAL-2256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1185)
> feat: don't block estimate error in sendTransaction

- .yarn/versions/7efa359a.yml
- packages/discover-accounts/index.js
- websites/doc/scripts/render-rpc-template.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1188)
> feat: import mnemonic without internet connection

- .yarn/versions/49e2f6ea.yml
- packages/popup/src/pages/AdvancedGas/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1192)
> fix: resend bug

- .yarn/versions/2c63d40a.yml
- packages/popup/src/pages/AdvancedGas/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1198)
> fix: nonce input check bug

- .yarn/versions/6983fece.yml
- packages/popup/src/pages/History/components/HistoryItem.js
PORTAL-3333
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1206)
> fix: fix PORTAL-3333

- .yarn/versions/4c5b8d95.yml
- packages/popup/src/components/GasCost.js
- packages/popup/src/components/GasFee.js
- packages/popup/src/pages/AdvancedGas/index.js
1. PORTAL-3330
2. PORTAL-3329
3. PORTAL-3331
4. PORTAL-3341
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1208)
> fix: some bugs

- .yarn/versions/523e3261.yml
- packages/popup/public/notification.html.mustache
- packages/popup/public/page.html.mustache
- packages/popup/public/popup.html.mustache
disable html translate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1214)
> feat: disable html translate

- .yarn/versions/db6b5f52.yml
- packages/rpcs/wallet_handleUnfinishedETHTx/index.js
PORTAL-3360
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1216)
> fix: wrong eth tx skippedChecked logic

- .yarn/versions/a2fd576c.yml
- packages/popup/src/components/Avatar.js
- packages/popup/src/pages/History/components/HistoryItem.js
- packages/popup/src/pages/History/components/TransitionDetail.js
fix PORTAL-3374
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1218)
> fix: fix PORTAL-3374

- .yarn/versions/a6ba2939.yml
- packages/popup/src/pages/AdvancedGas/index.js
- packages/popup/src/pages/EditGasFee/components/GasStation.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1230)
> fix: PORTAL-3377

- .yarn/versions/b33c3d21.yml
- packages/popup/src/pages/AdvancedGas/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1232)
> fix: PORTAL-3389

- .yarn/versions/32dfc1a4.yml
- packages/popup/src/pages/History/components/HistoryBalance.js
- packages/popup/src/pages/History/components/TransitionDetail.js
PORTAL-3394
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1234)
> fix: fix PORTAL-3394

- .yarn/versions/d5d82010.yml
- packages/popup/src/pages/AdvancedGas/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1235)
> fix: PORTAL-3395

- .yarn/versions/6af4e219.yml
- packages/popup/src/pages/AdvancedGas/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1240)
> fix: big number error in conflux testnet

- .yarn/versions/7efb32ca.yml
- packages/popup/src/pages/ResendTransaction/index.js
PORTAL-3335
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1243)
> fix: fix PORTAL-3335

- .yarn/versions/5e9a0ecc.yml
- packages/popup/src/components/TextField.js
- packages/popup/src/pages/History/components/HistoryItem.js
- packages/popup/src/pages/History/components/TransitionDetail.js
1.PORTAL-3405 
2.PORTAL-3407
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1248)
> fix: fix PORTAL-3405 and PORTAL-3407

- .yarn/versions/78a5ee04.yml
- packages/popup/src/pages/History/components/HistoryItem.js
refactor gas symbol
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1250)
> refactor: refactor gas symbol

- .yarn/versions/c8b1f15d.yml
- packages/popup/src/components/GasFee.js
- packages/popup/src/hooks/useApi.js
- packages/popup/src/pages/AdvancedGas/components/CustomGasPrice.js
- packages/popup/src/pages/AdvancedGas/index.js
- packages/popup/src/pages/EditGasFee/components/GasStation.js
- packages/popup/src/pages/EditGasFee/index.js
- packages/popup/src/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1252)
> fix: fix espace symbol

- .env
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1255)
> chore: next version 2.4.0

- .yarn/versions/6a64ee9c.yml
- packages/background/package.json
- packages/background/src/rpc-engine-opts.js
- packages/rpcs/wallet_sendTransaction/index.js
- packages/rpcs/wallet_sendTransactionWithAction/README.md
- packages/rpcs/wallet_sendTransactionWithAction/doc.js
- packages/rpcs/wallet_sendTransactionWithAction/index.js
- packages/rpcs/wallet_sendTransactionWithAction/package.json
- yarn.lock
params: {tx: <params of wallet_sendTransaction>, action: <'cancel' or 'speedUp'>}
PORTAL-3372
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1244)
> feat: add walelt_sendTransactionWithAction

- .yarn/versions/69f4c26b.yml
- packages/rpcs/wallet_sendTransactionWithAction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1257)
> fix: speedUp -> speedup

- .yarn/versions/99f6c58e.yml
- packages/popup/src/components/AlertMessage.js
- packages/popup/src/pages/ConfirmTransaction/index.js
- packages/popup/src/pages/ResendTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1260)
> feat: PORTAL-3421

- .yarn/versions/6a84ae86.yml
- packages/background/src/db-schema.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1262)
> fix: can't read sendAction in tx.txExtra

- .yarn/versions/a580b314.yml
- packages/background/src/db-schema.js
- packages/db/src/main/cfxjs/db/queries.cljs
PORTAL-3423
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1263)
> feat: add tx.pendingAt

- .yarn/versions/53680888.yml
- packages/rpcs/wallet_addNetwork/index.js
- packages/rpcs/wallet_updateNetwork/index.js
PORTAL-3433
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1266)
> feat: support alter builtin network endpoint

- .yarn/versions/b222e67e.yml
- packages/test-helpers/package.json
- yarn.lock
PORTAL-3043
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1267)
> chore: use conflux-rust v2.0.3 for tests

- .yarn/versions/b1e5d125.yml
- packages/popup/src/constants/rpcMethods.js
- packages/popup/src/locales/en.js
- packages/popup/src/locales/fr.js
- packages/popup/src/locales/ru.js
- packages/popup/src/locales/uk.js
- packages/popup/src/locales/zh.js
- packages/popup/src/pages/EditGasFee/index.js
- packages/popup/src/pages/History/components/HistoryItem.js
- packages/popup/src/pages/History/components/ResendButtons.js
- packages/popup/src/pages/History/components/TransitionDetail.js
- packages/popup/src/pages/History/index.js
- packages/popup/src/pages/ResendTransaction/index.js
1.PORTAL-3357 
2.PORTAL-3372
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1269)
> feat: add PORTAL-3357 and  PORTAL-3372

- .yarn/versions/ad057d61.yml
- packages/popup/src/components/NetworkContent.js
- packages/popup/src/hooks/useApi.js
- packages/popup/src/pages/NetworkDetail/index.js
- packages/popup/src/pages/NetworkManagement/index.js
- packages/rpcs/wallet_addNetwork/index.js
PORTAL-3432
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1271)
> feat:  optimise resend tx and network management

- .yarn/versions/d1b38f5b.yml
- packages/background/src/index.integration.test.js
- packages/json-rpc-error/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1273)
> fix: integration test for 2.0.3, error message

- .github/mergify.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1276)
> ci: more checks for auto merge

- .yarn/versions/1072fb86.yml
- packages/db/src/main/cfxjs/db/queries.cljs
PORTAL-3397
Signed-off-by: yqrashawn <namy.19@gmail.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1275)
> fix: handle duplicate external tx hash

- .yarn/versions/6246c5ce.yml
- packages/rpcs/wallet_addNetwork/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1278)
> fix: update network change builtin to cacheTime

- .yarn/versions/50beb6ce.yml
- packages/popup/src/components/AlertMessage.js
- packages/popup/src/hooks/index.js
- packages/popup/src/pages/ConfirmTransaction/index.js
- packages/popup/src/pages/SendTransaction/components/TokenAndAmount.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1279)
> feat: PORTAL-3038

- .yarn/versions/ad057d61.yml
- packages/popup/src/components/NetworkContent.js
- packages/popup/src/components/TitleNav.js
- packages/popup/src/constants/index.js
- packages/popup/src/locales/en.js
- packages/popup/src/locales/fr.js
- packages/popup/src/locales/ru.js
- packages/popup/src/locales/uk.js
- packages/popup/src/locales/zh.js
- packages/popup/src/pages/Home/components/NetworkList.js
- packages/popup/src/pages/NetworkDetail/index.js
1.PORTAL-3441
2.PORTAL-3432
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1283)
> feat: edit builtin rpc url

- .yarn/versions/700fbb16.yml
- packages/popup/src/pages/Home/components/CrossSpaceButton.js
- packages/popup/src/pages/Home/index.js
- packages/popup/src/pages/SendTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1285)
> fix: reset max mode when token change

- .yarn/versions/f3e3886c.yml
- packages/popup/src/hooks/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1289)
> fix: PORTAL-3453

- .yarn/versions/37fb0d7d.yml
- packages/popup/src/pages/AdvancedGas/index.js
- packages/popup/src/pages/SendTransaction/components/TokenAndAmount.js
1. PORTAL-3458
2. add some debug info for PORTAL-3457
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1292)
> fix: fix some bugs

- .yarn/versions/82dc3c4e.yml
- packages/db/src/main/cfxjs/db/queries.cljs
PORTAL-3397
Signed-off-by: yqrashawn <namy.19@gmail.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1295)
> fix: for get to exec tx

- .yarn/versions/06c056ed.yml
- packages/popup/src/pages/SendTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1297)
> fix: PORTAL-3464

- .yarn/versions/b58c9300.yml
- packages/popup/src/pages/EditGasFee/index.js
- packages/popup/src/pages/History/components/HistoryItem.js
- packages/popup/src/pages/History/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1299)
> fix: advanced gas init bug

- .yarn/versions/ac125c1f.yml
- packages/popup/src/pages/SendTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1303)
> fix: reset from advanced to default when change token

- .yarn/versions/fd0131fe.yml
- packages/popup/src/pages/ConfirmTransaction/index.js
- packages/popup/src/pages/EditGasFee/index.js
- packages/popup/src/pages/SendTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1305)
> fix: clear advanced gas setting when back to send transaction

- .env
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1309)
> chore: version-2.5.0

- .github/workflows/version-check.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1315)
> feat: modify version check

- .env.development
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1326)
> chore: test

- .env
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1332)
> chore: update version: 2.6.0

- .env
- .yarn/versions/a49b0891.yml
- packages/popup/src/pages/DappSwitchNetwork/index.js
- packages/popup/src/pages/NetworkDetail/index.js
- packages/popup/src/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1335)
> feat: hide limit key

- .env
- .yarn/versions/a49b0891.yml
- packages/popup/src/pages/DappSwitchNetwork/index.js
- packages/popup/src/pages/NetworkDetail/index.js
- packages/popup/src/utils/index.js
limit key
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1337)
> feat: Release version:2.5.1

- .env
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1339)
> chore: 2.6.0

- .yarn/versions/c0682248.yml
- packages/popup/src/components/NsNameLabel.js
- packages/popup/src/pages/History/components/TransitionDetail.js
- packages/popup/src/pages/SendTransaction/components/AddressWithAlternativeName.js
- packages/popup/src/pages/SendTransaction/components/ToAddressInput.js
- packages/popup/src/pages/SendTransaction/index.js
1.PORTAL-3495
2.PORTAL-3494
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1344)
> fix: fix ui bugs

- .yarn/versions/d7c3bf49.yml
- packages/did/cns/abis/ReverseRecords.json
- packages/did/cns/index.js
- packages/popup/snowpack.config.cjs
replace cns contract and update reverse lookup function
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1346)
> feat: replace cns contract

- package.json
- scripts/build/bg.js
- scripts/build/popup.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/helios/1348)
> fix: esbuild bug fix for web3.js

- .yarn/versions/e54b7dce.yml
- packages/did/cns/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1353)
> feat: update cns testnet address

- .yarn/versions/82a5377f.yml
- packages/did/cns/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1356)
> feat: cns mainnet address

- .env
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1359)
> chore: modify version

- .yarn/versions/05922ea9.yml
- packages/popup/src/utils/index.js
fix PORTAL-3513
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1361)
> Fix: PORTAL-3513

- .yarn/versions/ad6fcfa2.yml
- packages/ledger/conflux.js
- packages/ledger/ethereum.js
- packages/ledger/index.js
- packages/rpcs/cfx_signTransaction/index.js
- packages/rpcs/cfx_signTxWithLedgerNanoS/index.js
- packages/rpcs/eth_signTransaction/index.js
- packages/rpcs/eth_signTxWithLedgerNanoS/index.js
- packages/rpcs/wallet_importHardwareWalletAccountGroupOrAccount/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1360)
> feat: support ledger s plus

- .yarn/versions/37288a54.yml
- packages/did/cns/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1363)
> fix(PORTAL-3513): do not check chainID on CNS

- .yarn/versions/ba5477dd.yml
- packages/rpcs/eth_signTxWithLedgerNanoS/index.js
- packages/rpcs/eth_signTxWithLedgerNanoS/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1368)
> feat: support EIP1559 when sign with ledger

- scripts/before_all.js
modify Manifest
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1370)
> feat: enable running WebAssembly

- scripts/before_all.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1373)
> fix: add comma in manifest file

- .yarn/versions/649332a3.yml
- packages/estimate-tx/eth.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1375)
> fix: fix eth gas fee bug

- .yarn/versions/649332a3.yml
- packages/estimate-tx/eth.js
- packages/popup/src/hooks/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1377)
> fix: update balance max bug

- .vscode/launch.json
- .yarn/versions/c0285415.yml
- packages/background/package.json
- packages/background/src/index.js
- packages/extension-runtime/background.js
- packages/extension-runtime/package.json
- packages/popup/package.json
- packages/popup/src/index.js
- packages/rpc-engine/index.js
- packages/rpc-engine/middlewares/call-rpc.js
- packages/rpc-engine/middlewares/fetch.js
- packages/rpc-engine/middlewares/inject-rpc-store.js
- packages/rpc-engine/middlewares/inject-wallet-db.js
- packages/rpc-engine/middlewares/validate-json-rpc-format.js
- packages/rpc-engine/middlewares/validate-rpc-data.js
- packages/rpc-engine/middlewares/validate-rpc-params.js
- packages/rpc-engine/src/error.js
- packages/rpcs/wallet_addVault/index.js
- packages/rpcs/wallet_addVault/package.json
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.test.js
- packages/rpcs/wallet_handleUnfinishedCFXTx/package.json
- packages/rpcs/wallet_handleUnfinishedETHTx/index.js
- packages/rpcs/wallet_handleUnfinishedETHTx/package.json
- packages/rpcs/wallet_refetchBalance/index.js
- packages/rpcs/wallet_refetchBalance/package.json
- packages/rpcs/wallet_setCurrentNetwork/index.js
- packages/rpcs/wallet_setCurrentNetwork/package.json
- packages/service-worker/index.ts
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1388)
> chore: remove sentry

- .github/workflows/comment-on-release.yaml
- .github/workflows/deploy-basic-dapp-demo.yaml
- .github/workflows/deploy-doc.yaml
- .github/workflows/opti-image.yaml
- .github/workflows/pre-release.yaml
- .github/workflows/prod-release.yaml
- .github/workflows/publish-npm-package.yaml
- .github/workflows/push-check.yaml
- .github/workflows/version-check.yaml
- .yarn/versions/a3fe6540.yml
- packages/confluxscan-api/contract.js
- Updated Node.js version to 22 in GitHub Actions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1392)
> chore: update node version in github action

- .yarn/versions/a3fe6540.yml
- packages/addr-by-network/index.js
- packages/addr-by-network/index.test.js
- Updated `addr-by-network` test and add jsdoc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1394)
> chore: update addr-by-network test

- .github/workflows/pre-release.yaml
- .github/workflows/prod-release.yaml
- .yarn/versions/470ba7dd.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1400)
> build: update github action env

- .yarn/versions/482336a5.yml
- packages/popup/src/components/StretchInput.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1404)
> Fix search input height error

- .yarn/versions/470ba7dd.yml
- .yarn/versions/482336a5.yml
- package.json
- packages/browser-extension/package.json
- packages/popup/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1406)
> release 2.7.4

- packages/rpcs/wallet_handleUnfinishedETHTx/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1408)
> fix: remove if in tx send error handler

- .yarn/versions/892784a9.yml
- packages/background/package.json
- packages/background/src/index.integration.test.js
- packages/background/src/rpc-engine-opts.js
- packages/rpcs/cfx_maxPriorityFeePerGas/README.md
- packages/rpcs/cfx_maxPriorityFeePerGas/doc.js
- packages/rpcs/cfx_maxPriorityFeePerGas/index.js
- packages/rpcs/cfx_maxPriorityFeePerGas/package.json
- yarn.lock
Add cfx_maxPriorityFeePerGas RPC
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1417)
> feat:  add cfx_maxPriorityFeePerGas RPC

- .yarn/versions/f3a29056.yml
- packages/background/package.json
- packages/background/src/index.integration.test.js
- packages/background/src/rpc-engine-opts.js
- packages/rpcs/cfx_getFeeBurnt/README.md
- packages/rpcs/cfx_getFeeBurnt/doc.js
- packages/rpcs/cfx_getFeeBurnt/index.js
- packages/rpcs/cfx_getFeeBurnt/package.json
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1420)
> feat: add cfx_getFeeBurnt rpc

- .yarn/versions/4e981df6.yml
- packages/background/src/index.integration.test.js
- packages/rpcs/cfx_estimateGasAndCollateral/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1422)
> Cfx estimate gas and collateral

- .yarn/versions/5cc0b5ea.yml
- package.json
- scripts/webpack.config.cjs
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1425)
> fix error when input the espace address

- .yarn/versions/5cc0b5ea.yml
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1426)
> chore: apply version

- .yarn/versions/ceab6a43.yml
- packages/manifest/manifestv2.json
- packages/manifest/manifestv3.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1427)
> chore: add name for local dev

- .yarn/versions/11720844.yml
- packages/rpc-engine/middlewares/validate-rpc-params.js
- packages/rpcs/cfx_signTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1443)
> fix: add type to core space tx and fix type format

- .yarn/versions/b7e895ef.yml
- packages/inpage/eip-6963.js
- packages/inpage/package.json
- packages/inpage/setup-inpage-provider.js
- packages/inpage/setup-inpage-provider.test.js
- yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1446)
> feat: support eip-6963

- .github/workflows/pre-release.yaml
- .github/workflows/prod-release.yaml
- .yarn/versions/7f49ff5b.yml
- .yarn/versions/c4d6a83d.yml
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1449)
> chore: update build script

- .yarn/versions/202cd75a.yml
- packages/rpcs/wallet_createAccount/index.js
- packages/rpcs/wallet_deleteAccount/index.js
- packages/rpcs/wallet_deleteAccountGroup/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1453)
> fix: check group before insert account

- .yarn/versions/53c8460f.yml
- packages/rpcs/cfx_estimate1559Fee/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1456)
> chore: add estimatedBaseFee to gasInfo

- .yarn/versions/c1cc0943.yml
- packages/popup/src/hooks/index.js
- packages/popup/src/pages/ConfirmTransaction/components/AddressCard.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1458)
> fix: when call a contract with a valid "value" parameter should display in confirm page

- .yarn/versions/9e6442d9.yml
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.js
- packages/rpcs/wallet_handleUnfinishedCFXTx/index.test.js
- packages/rpcs/wallet_handleUnfinishedETHTx/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1461)
> fix: test case

- .github/workflows/pre-release.yaml
- .github/workflows/prod-release.yaml
- .yarn/versions/4c2952f1.yml
- packages/inner-utils/env.js
- packages/popup/src/hooks/useApi.js
- packages/popup/src/pages/About/index.js
- packages/rpcs/wallet_getFluentMetadata/index.js
- scripts/webpack.config.cjs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1465)
> chore: update fluent view version

- .github/mergify.yml
- .yarn/versions/5ca621c7.yml
- packages/inner-utils/env.js
This change has been made by @iosh from the Mergify config editor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1468)
> ci(Mergify): configuration update

- .yarn/versions/117003c2.yml
- packages/popup/src/pages/ResendTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1470)
> fix: PORTAL-3572

- .github/mergify.yml
- .yarn/versions/8a7d302f.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1473)
> chore: update mergify config

- .yarn/versions/570cf76a.yml
- packages/account/index.js
- packages/utils/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1472)
> chore: add check to add private key to wallet

- .yarn/versions/01a87f4a.yml
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1483)
> chore: bump version

- .yarn/versions/1e7424d1.yml
- packages/popup/src/index.js
- packages/popup/src/pages/Error/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1488)
> fix: redirect to unlock page

- .github/workflows/publish-npm-package.yaml
- .yarn/versions/bea555df.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1497)
> build: fix yarn install error

- .yarn/versions/247b4abe.yml
- packages/popup/src/pages/CreateSeed/BackupSeed.js
- packages/popup/src/pages/CreateSeed/ConfirmSeed.js
- packages/popup/src/pages/CreateSeed/index.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1524)
> fix: sidebar seed ui

- .yarn/versions/5d9746ec.yml
- packages/rpcs/cfx_signTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1538)
> fix: check ledger connect before request

- .github/workflows/deploy-basic-dapp-demo.yaml
- .yarn/versions/8ac1a7fc.yml
- packages/popup/src/pages/RequestSignature/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1541)
> fix siwe bug

- .yarn/versions/ffae9ea0.yml
- packages/popup/src/index.js
- packages/popup/src/locales/en.js
- packages/popup/src/locales/fr.js
- packages/popup/src/locales/ru.js
- packages/popup/src/locales/uk.js
- packages/popup/src/locales/zh.js
- packages/popup/src/pages/RequestSignature/components/ConfirmInfo.js
- packages/popup/src/pages/RequestSignature/components/SignInSign.js
- packages/popup/src/pages/RequestSignature/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1543)
> chore: fix siwe sign

- .yarn/versions/ee21195a.yml
- package.json
- packages/popup/src/pages/RequestSignature/components/ConfirmInfo.js
- packages/popup/src/pages/RequestSignature/components/SignInSign.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1547)
> fix: fix package version and table css

- .yarn/versions/8f1510cd.yml
- packages/popup/src/pages/RequestSignature/components/ConfirmInfo.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1549)
> fix: add width to label

- .yarn/versions/60b84c39.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1555)
> chore: release 2.8.5

- .yarn/versions/0fb3d33d.yml
- packages/popup/src/pages/ConnectSite/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1561)
> chore: version check

- .yarn/versions/aa00b5c3.yml
- .yarn/versions/cd354ad9.yml
- packages/popup/src/pages/ConfirmTransaction/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/helios/1578)
> Confirm transaction
